# Generated by Django 4.2.7 on 2025-09-03 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Profil Adı")),
                (
                    "profile_code",
                    models.IntegerField(unique=True, verbose_name="Profil Kodu"),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("personel", "Personel"),
                            ("misafir", "Misafir"),
                            ("vip", "VIP"),
                            ("ultra", "Ultra Paket"),
                            ("ust", "Üst Paket"),
                        ],
                        default="personel",
                        max_length=20,
                    ),
                ),
                (
                    "upload_speed",
                    models.IntegerField(default=10, verbose_name="Upload Hızı (Mbps)"),
                ),
                (
                    "download_speed",
                    models.IntegerField(
                        default=10, verbose_name="Download Hızı (Mbps)"
                    ),
                ),
                ("duration_days", models.IntegerField(default=0, verbose_name="Gün")),
                ("duration_hours", models.IntegerField(default=0, verbose_name="Saat")),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, verbose_name="Dakika"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="Saniye"),
                ),
                (
                    "shared_users",
                    models.IntegerField(default=1, verbose_name="Paylaşılan Kullanıcı"),
                ),
                (
                    "max_concurrent_users",
                    models.IntegerField(
                        default=1, verbose_name="Maksimum Eşzamanlı Kullanıcı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Premium Profil"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
                "ordering": ["profile_code"],
                "unique_together": {("profile_code", "company")},
            },
        ),
        migrations.CreateModel(
            name="UserProfileAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Atama Tarihi"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif Atama"),
                ),
                (
                    "current_bandwidth_used",
                    models.BigIntegerField(
                        default=0, verbose_name="Kullanılan Bant Genişliği (bytes)"
                    ),
                ),
                (
                    "session_count",
                    models.IntegerField(default=0, verbose_name="Oturum Sayısı"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_management.userprofile",
                        verbose_name="Profil",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profil Ataması",
                "verbose_name_plural": "Kullanıcı Profil Atamaları",
                "unique_together": {("user", "company")},
            },
        ),
    ]
