# Generated by Django 4.2.7 on 2025-09-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0013_logkayit_cihaz_adi_logkayit_lokasyon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogVerificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Şablon Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "verification_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Doğrulama Kuralları"
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Zorunlu Alanlar"
                    ),
                ),
                (
                    "hash_algorithm",
                    models.CharField(
                        choices=[
                            ("MD5", "MD5"),
                            ("SHA1", "SHA1"),
                            ("SHA256", "SHA256"),
                        ],
                        default="SHA256",
                        max_length=20,
                        verbose_name="Hash Algoritması",
                    ),
                ),
                (
                    "auto_generate_report",
                    models.BooleanField(
                        default=True, verbose_name="Otomatik Rapor Oluştur"
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("CSV", "CSV"), ("JSON", "JSON")],
                        default="PDF",
                        max_length=10,
                        verbose_name="Rapor Formatı",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Doğrulama Şablonu",
                "verbose_name_plural": "Log Doğrulama Şablonları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LogVerificationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_name",
                    models.CharField(max_length=200, verbose_name="Oturum Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "uploaded_file",
                    models.FileField(
                        upload_to="log_verification/", verbose_name="Yüklenen Dosya"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Dosya Adı"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Dosya Boyutu (byte)"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Dosya Hash"
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("HASH_VERIFICATION", "Hash Doğrulama"),
                            ("SIGNATURE_VERIFICATION", "İmza Doğrulama"),
                            ("INTEGRITY_CHECK", "Bütünlük Kontrolü"),
                            ("COMPLETE_VERIFICATION", "Tam Doğrulama"),
                        ],
                        default="COMPLETE_VERIFICATION",
                        max_length=25,
                        verbose_name="Doğrulama Tipi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("PROCESSING", "İşleniyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="İlerleme (%)"),
                ),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="Toplam Kayıt"),
                ),
                (
                    "verified_records",
                    models.IntegerField(default=0, verbose_name="Doğrulanan Kayıt"),
                ),
                (
                    "failed_records",
                    models.IntegerField(default=0, verbose_name="Başarısız Kayıt"),
                ),
                (
                    "modified_records",
                    models.IntegerField(default=0, verbose_name="Değiştirilmiş Kayıt"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlama Zamanı"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Zamanı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Hata Detayları"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Doğrulama Oturumu",
                "verbose_name_plural": "Log Doğrulama Oturumları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogVerificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Log ID"),
                ),
                (
                    "log_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Log Zamanı"
                    ),
                ),
                (
                    "log_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Log Kaynağı"
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("VALID", "Geçerli"),
                            ("MODIFIED", "Değiştirilmiş"),
                            ("INVALID", "Geçersiz"),
                            ("MISSING", "Eksik"),
                            ("ERROR", "Hata"),
                        ],
                        max_length=20,
                        verbose_name="Sonuç Tipi",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=False, verbose_name="Geçerli"),
                ),
                (
                    "original_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Orijinal Hash"
                    ),
                ),
                (
                    "calculated_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hesaplanan Hash"
                    ),
                ),
                (
                    "hash_match",
                    models.BooleanField(default=False, verbose_name="Hash Eşleşiyor"),
                ),
                (
                    "has_signature",
                    models.BooleanField(default=False, verbose_name="İmza Var"),
                ),
                (
                    "signature_valid",
                    models.BooleanField(default=False, verbose_name="İmza Geçerli"),
                ),
                (
                    "signature_authority",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="İmza Otoritesi"
                    ),
                ),
                (
                    "verification_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Doğrulama Detayları"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Doğrulama Zamanı"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="log_verification.logverificationsession",
                        verbose_name="Doğrulama Oturumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Doğrulama Sonucu",
                "verbose_name_plural": "Log Doğrulama Sonuçları",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="LogIntegrityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SUMMARY", "Özet Rapor"),
                            ("DETAILED", "Detaylı Rapor"),
                            ("COMPLIANCE", "Uyumluluk Raporu"),
                            ("EVIDENCE", "İbraz Raporu"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                (
                    "report_title",
                    models.CharField(max_length=200, verbose_name="Rapor Başlığı"),
                ),
                ("report_content", models.TextField(verbose_name="Rapor İçeriği")),
                (
                    "report_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Rapor Verisi"
                    ),
                ),
                (
                    "total_records_analyzed",
                    models.IntegerField(
                        default=0, verbose_name="Analiz Edilen Toplam Kayıt"
                    ),
                ),
                (
                    "valid_records_count",
                    models.IntegerField(default=0, verbose_name="Geçerli Kayıt Sayısı"),
                ),
                (
                    "modified_records_count",
                    models.IntegerField(
                        default=0, verbose_name="Değiştirilmiş Kayıt Sayısı"
                    ),
                ),
                (
                    "invalid_records_count",
                    models.IntegerField(
                        default=0, verbose_name="Geçersiz Kayıt Sayısı"
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="log_reports/",
                        verbose_name="Rapor Dosyası",
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("CSV", "CSV"),
                            ("JSON", "JSON"),
                            ("XML", "XML"),
                        ],
                        default="PDF",
                        max_length=10,
                        verbose_name="Rapor Formatı",
                    ),
                ),
                (
                    "compliance_score",
                    models.IntegerField(default=0, verbose_name="Uyumluluk Skoru (%)"),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Uyumlu"),
                            ("PARTIALLY_COMPLIANT", "Kısmen Uyumlu"),
                            ("NON_COMPLIANT", "Uyumsuz"),
                        ],
                        default="NON_COMPLIANT",
                        max_length=20,
                        verbose_name="Uyumluluk Durumu",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="log_verification.logverificationsession",
                        verbose_name="Doğrulama Oturumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Bütünlük Raporu",
                "verbose_name_plural": "Log Bütünlük Raporları",
                "ordering": ["-generated_at"],
            },
        ),
    ]
