# Generated by Django 4.2.7 on 2025-09-08 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("log_kayit", "0013_logkayit_cihaz_adi_logkayit_lokasyon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                            ("EMERGENCY", "Acil"),
                        ],
                        max_length=15,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaylar"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("ACKNOWLEDGED", "Kabul Edildi"),
                            ("RESOLVED", "Çözüldü"),
                            ("SUPPRESSED", "Bastırıldı"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tetiklenme Zamanı"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kabul Zamanı"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                (
                    "notifications_sent",
                    models.IntegerField(default=0, verbose_name="Gönderilen Bildirim"),
                ),
                (
                    "last_notification_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Bildirim"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alarms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kabul Eden",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alarms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çözen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm Olayı",
                "verbose_name_plural": "Alarm Olayları",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AlarmSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bastırma Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "alarm_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Alarm Tipleri"
                    ),
                ),
                (
                    "severity_levels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Önem Seviyeleri"
                    ),
                ),
                (
                    "source_devices",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Kaynak Cihazlar"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Başlama Zamanı")),
                ("end_time", models.DateTimeField(verbose_name="Bitiş Zamanı")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm Bastırma",
                "verbose_name_plural": "Alarm Bastırmaları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlarmRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Alarm Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "alarm_type",
                    models.CharField(
                        choices=[
                            ("SIGNING_FAILED", "İmzalama Başarısız"),
                            ("DISK_FULL", "Disk Dolu"),
                            ("NTP_DRIFT", "NTP Sapması"),
                            ("LOG_FLOW_STOPPED", "Log Akışı Durdu"),
                            ("DEVICE_OFFLINE", "Cihaz Çevrimdışı"),
                            ("HIGH_CPU_USAGE", "Yüksek CPU Kullanımı"),
                            ("HIGH_MEMORY_USAGE", "Yüksek Bellek Kullanımı"),
                            ("NETWORK_ERROR", "Ağ Hatası"),
                            ("SECURITY_THREAT", "Güvenlik Tehdidi"),
                            ("COMPLIANCE_VIOLATION", "Uyumluluk İhlali"),
                            ("BACKUP_FAILED", "Yedekleme Başarısız"),
                            ("CUSTOM", "Özel"),
                        ],
                        max_length=30,
                        verbose_name="Alarm Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                            ("EMERGENCY", "Acil"),
                        ],
                        max_length=15,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                (
                    "condition",
                    models.TextField(help_text="Alarm koşulu", verbose_name="Koşul"),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Eşik Değeri"
                    ),
                ),
                (
                    "time_window_minutes",
                    models.IntegerField(
                        default=5, verbose_name="Zaman Penceresi (dakika)"
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(default=True, verbose_name="E-posta Bildirimi"),
                ),
                (
                    "notify_sms",
                    models.BooleanField(default=False, verbose_name="SMS Bildirimi"),
                ),
                (
                    "notify_webhook",
                    models.BooleanField(
                        default=False, verbose_name="Webhook Bildirimi"
                    ),
                ),
                (
                    "notify_dashboard",
                    models.BooleanField(
                        default=True, verbose_name="Dashboard Bildirimi"
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış e-posta listesi",
                        verbose_name="E-posta Alıcıları",
                    ),
                ),
                (
                    "sms_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış telefon listesi",
                        verbose_name="SMS Alıcıları",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook URL"),
                ),
                (
                    "repeat_notification",
                    models.BooleanField(default=True, verbose_name="Tekrar Bildirim"),
                ),
                (
                    "repeat_interval_minutes",
                    models.IntegerField(
                        default=60, verbose_name="Tekrar Aralığı (dakika)"
                    ),
                ),
                (
                    "max_repeat_count",
                    models.IntegerField(
                        default=5, verbose_name="Maksimum Tekrar Sayısı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Etkin")),
                (
                    "trigger_count",
                    models.IntegerField(default=0, verbose_name="Tetiklenme Sayısı"),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Tetiklenme"
                    ),
                ),
                (
                    "last_notification_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Bildirim"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm Kuralı",
                "verbose_name_plural": "Alarm Kuralları",
                "ordering": ["-severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="AlarmNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-posta"),
                            ("SMS", "SMS"),
                            ("WEBHOOK", "Webhook"),
                            ("DASHBOARD", "Dashboard"),
                            ("SLACK", "Slack"),
                            ("TEAMS", "Microsoft Teams"),
                            ("TELEGRAM", "Telegram"),
                        ],
                        max_length=20,
                        verbose_name="Bildirim Tipi",
                    ),
                ),
                ("recipient", models.CharField(max_length=200, verbose_name="Alıcı")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=300, verbose_name="Konu"),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("SENT", "Gönderildi"),
                            ("FAILED", "Başarısız"),
                            ("DELIVERED", "Teslim Edildi"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderilme Zamanı"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Teslim Zamanı"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="Deneme Sayısı"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="alarm_integration.alarmevent",
                        verbose_name="Alarm Olayı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm Bildirimi",
                "verbose_name_plural": "Alarm Bildirimleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="alarmevent",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alarm_integration.alarmrule",
                verbose_name="Alarm Kuralı",
            ),
        ),
        migrations.CreateModel(
            name="AlarmStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "total_alarms",
                    models.IntegerField(default=0, verbose_name="Toplam Alarm"),
                ),
                (
                    "critical_alarms",
                    models.IntegerField(default=0, verbose_name="Kritik Alarm"),
                ),
                (
                    "high_alarms",
                    models.IntegerField(default=0, verbose_name="Yüksek Alarm"),
                ),
                (
                    "medium_alarms",
                    models.IntegerField(default=0, verbose_name="Orta Alarm"),
                ),
                (
                    "low_alarms",
                    models.IntegerField(default=0, verbose_name="Düşük Alarm"),
                ),
                (
                    "active_alarms",
                    models.IntegerField(default=0, verbose_name="Aktif Alarm"),
                ),
                (
                    "acknowledged_alarms",
                    models.IntegerField(default=0, verbose_name="Kabul Edilen Alarm"),
                ),
                (
                    "resolved_alarms",
                    models.IntegerField(default=0, verbose_name="Çözülen Alarm"),
                ),
                (
                    "total_notifications",
                    models.IntegerField(default=0, verbose_name="Toplam Bildirim"),
                ),
                (
                    "successful_notifications",
                    models.IntegerField(default=0, verbose_name="Başarılı Bildirim"),
                ),
                (
                    "failed_notifications",
                    models.IntegerField(default=0, verbose_name="Başarısız Bildirim"),
                ),
                (
                    "average_response_time_minutes",
                    models.FloatField(
                        default=0, verbose_name="Ortalama Yanıt Süresi (dakika)"
                    ),
                ),
                (
                    "average_resolution_time_minutes",
                    models.FloatField(
                        default=0, verbose_name="Ortalama Çözüm Süresi (dakika)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm İstatistiği",
                "verbose_name_plural": "Alarm İstatistikleri",
                "ordering": ["-date"],
                "unique_together": {("company", "date")},
            },
        ),
    ]
