# Generated by Django 3.2.6 on 2025-06-19 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_kayit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Yetkili Kişi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='logkayit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='log_kayit.company', verbose_name='Firma'),
        ),
    ]
