# Generated by Django 3.2.6 on 2025-06-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_kayit', '0004_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kvkk_text',
            field=models.TextField(blank=True, null=True, verbose_name='KVKK Metni'),
        ),
        migrations.AddField(
            model_name='company',
            name='login_info_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Giriş Formu Açıklaması'),
        ),
        migrations.AddField(
            model_name='company',
            name='theme_color',
            field=models.CharField(blank=True, default='#0d6efd', max_length=7, null=True, verbose_name='Tema Rengi (hex)'),
        ),
    ]
