# Generated by Django 3.2.6 on 2025-06-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_kayit', '0005_auto_20250619_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='logkayit',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Şüpheli/Geçersiz Giriş'),
        ),
    ]
