# Generated by Django 3.2.6 on 2025-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_kayit', '0006_logkayit_is_suspicious'),
    ]

    operations = [
        migrations.AddField(
            model_name='logkayit',
            name='kimlik_turu',
            field=models.CharField(choices=[('TC', 'TC Kimlik'), ('PASAPORT', 'Pasaport')], default='TC', max_length=16, verbose_name='Kimlik Türü'),
        ),
        migrations.AddField(
            model_name='logkayit',
            name='pasaport_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Pasaport No'),
        ),
        migrations.AlterField(
            model_name='logkayit',
            name='tc_no',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No'),
        ),
    ]
