# Generated by Django 3.2.6 on 2025-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_kayit', '0007_auto_20250619_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='logkayit',
            name='pasaport_ulkesi',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Pasaport Ülkesi'),
        ),
    ]
