# Generated by Django 3.2.6 on 2025-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_kayit', '0008_logkayit_pasaport_ulkesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_foreigners',
            field=models.BooleanField(default=True, verbose_name='Yabancı Girişine İzin Ver'),
        ),
    ]
