# Generated by Django 3.2.6 on 2025-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_kayit', '0009_company_allow_foreigners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Kodu'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Firma Yöneticisi'), ('staff', 'Personel'), ('viewer', 'Sadece Görüntüleyici')], default='viewer', max_length=16, verbose_name='Rol'),
        ),
    ]
