# Generated by Django 4.2.7 on 2025-09-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("log_kayit", "0011_alter_company_options_alter_logkayit_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logkayit",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="log_kayit.company",
                verbose_name="Firma",
            ),
        ),
    ]
