# Generated by Django 4.2.7 on 2025-09-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_kayit", "0012_alter_logkayit_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="logkayit",
            name="cihaz_adi",
            field=models.CharField(
                blank=True,
                help_text="Erişim yapılan cihaz",
                max_length=100,
                verbose_name="Cihaz Adı",
            ),
        ),
        migrations.AddField(
            model_name="logkayit",
            name="lokasyon",
            field=models.CharField(
                blank=True,
                help_text="Fiziksel konum bilgisi",
                max_length=200,
                verbose_name="Lokasyon",
            ),
        ),
        migrations.AddField(
            model_name="logkayit",
            name="nat_ip_adresi",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Network Address Translation IP adresi",
                null=True,
                verbose_name="NAT IP Adresi",
            ),
        ),
        migrations.AddField(
            model_name="logkayit",
            name="nat_port",
            field=models.IntegerField(
                blank=True,
                help_text="Network Address Translation port numarası",
                null=True,
                verbose_name="NAT Port",
            ),
        ),
    ]
