# Generated by Django 4.2.7 on 2025-09-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firewall_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firewallrule",
            name="destination_ip",
            field=models.CharField(
                blank=True, default="ANY", max_length=50, verbose_name="Hedef IP"
            ),
        ),
        migrations.AlterField(
            model_name="firewallrule",
            name="destination_port",
            field=models.CharField(
                blank=True, default="ANY", max_length=20, verbose_name="Hedef Port"
            ),
        ),
        migrations.AlterField(
            model_name="firewallrule",
            name="source_ip",
            field=models.CharField(
                blank=True, default="ANY", max_length=50, verbose_name="Kaynak IP"
            ),
        ),
        migrations.AlterField(
            model_name="firewallrule",
            name="source_port",
            field=models.CharField(
                blank=True, default="ANY", max_length=20, verbose_name="Kaynak Port"
            ),
        ),
    ]
