# Generated by Django 4.2.7 on 2025-09-06 13:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0012_alter_logkayit_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyslogServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Sunucu Adı")),
                ("host", models.GenericIPAddressField(verbose_name="Host IP")),
                ("port", models.IntegerField(default=514, verbose_name="Port")),
                (
                    "protocol",
                    models.CharField(
                        choices=[("UDP", "UDP"), ("TCP", "TCP"), ("TLS", "TLS")],
                        default="UDP",
                        max_length=10,
                        verbose_name="Protokol",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=False, verbose_name="TLS Kullan"),
                ),
                (
                    "certificate_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Sertifika Yolu"
                    ),
                ),
                (
                    "private_key_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Özel Anahtar Yolu"
                    ),
                ),
                (
                    "allowed_facilities",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış facility listesi",
                        verbose_name="İzin Verilen Facility'ler",
                    ),
                ),
                (
                    "allowed_priorities",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış priority listesi",
                        verbose_name="İzin Verilen Priority'ler",
                    ),
                ),
                (
                    "max_connections",
                    models.IntegerField(default=1000, verbose_name="Maksimum Bağlantı"),
                ),
                (
                    "buffer_size",
                    models.IntegerField(default=100, verbose_name="Buffer Boyutu (MB)"),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=1000, verbose_name="Toplu İşlem Boyutu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_running",
                    models.BooleanField(default=False, verbose_name="Çalışıyor"),
                ),
                (
                    "total_logs_received",
                    models.BigIntegerField(default=0, verbose_name="Toplam Alınan Log"),
                ),
                (
                    "total_connections",
                    models.IntegerField(default=0, verbose_name="Toplam Bağlantı"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Aktivite"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syslog Sunucu",
                "verbose_name_plural": "Syslog Sunucuları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyslogFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Filtre Adı")),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("FACILITY", "Facility"),
                            ("PRIORITY", "Priority"),
                            ("HOSTNAME", "Hostname"),
                            ("PROGRAM", "Program"),
                            ("MESSAGE", "Mesaj İçeriği"),
                            ("IP", "IP Adresi"),
                            ("REGEX", "Regex Pattern"),
                        ],
                        max_length=20,
                        verbose_name="Filtre Tipi",
                    ),
                ),
                (
                    "filter_value",
                    models.CharField(max_length=500, verbose_name="Filtre Değeri"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ACCEPT", "Kabul Et"),
                            ("REJECT", "Reddet"),
                            ("FORWARD", "İlet"),
                            ("STORE", "Sakla"),
                            ("ALERT", "Uyarı Ver"),
                        ],
                        default="ACCEPT",
                        max_length=20,
                        verbose_name="Aksiyon",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Düşük sayı = yüksek öncelik",
                        verbose_name="Öncelik",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syslog Filtresi",
                "verbose_name_plural": "Syslog Filtreleri",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="SyslogClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="İstemci Adı")),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("CISCO", "Cisco"),
                            ("MIKROTIK", "MikroTik"),
                            ("FORTINET", "Fortinet"),
                            ("WINDOWS", "Windows"),
                            ("LINUX", "Linux"),
                            ("CUSTOM", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="İstemci Tipi",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="MAC Adresi"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Hostname"
                    ),
                ),
                (
                    "facility",
                    models.IntegerField(default=16, verbose_name="Varsayılan Facility"),
                ),
                (
                    "priority",
                    models.IntegerField(default=6, verbose_name="Varsayılan Priority"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Çevrimiçi"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Görülme"
                    ),
                ),
                (
                    "total_messages_sent",
                    models.BigIntegerField(
                        default=0, verbose_name="Toplam Gönderilen Mesaj"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Mesaj Zamanı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "syslog_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syslog_server.syslogserver",
                        verbose_name="Syslog Sunucu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syslog İstemcisi",
                "verbose_name_plural": "Syslog İstemcileri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyslogAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Uyarı Adı")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("THRESHOLD", "Eşik Aşımı"),
                            ("PATTERN", "Pattern Eşleşmesi"),
                            ("FREQUENCY", "Frekans Aşımı"),
                            ("ANOMALY", "Anomali Tespiti"),
                        ],
                        max_length=20,
                        verbose_name="Uyarı Tipi",
                    ),
                ),
                (
                    "condition",
                    models.TextField(help_text="Uyarı koşulu", verbose_name="Koşul"),
                ),
                (
                    "threshold_value",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Eşik Değeri"
                    ),
                ),
                (
                    "time_window",
                    models.IntegerField(
                        default=5, verbose_name="Zaman Penceresi (dakika)"
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(default=True, verbose_name="E-posta Bildirimi"),
                ),
                (
                    "notify_sms",
                    models.BooleanField(default=False, verbose_name="SMS Bildirimi"),
                ),
                (
                    "notification_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış e-posta listesi",
                        verbose_name="Bildirim Alıcıları",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "last_triggered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Tetiklenme"
                    ),
                ),
                (
                    "trigger_count",
                    models.IntegerField(default=0, verbose_name="Tetiklenme Sayısı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syslog Uyarısı",
                "verbose_name_plural": "Syslog Uyarıları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyslogStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "hour",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                        verbose_name="Saat",
                    ),
                ),
                (
                    "total_messages",
                    models.BigIntegerField(default=0, verbose_name="Toplam Mesaj"),
                ),
                (
                    "messages_by_facility",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Facility Bazında Mesajlar",
                    ),
                ),
                (
                    "messages_by_priority",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Priority Bazında Mesajlar",
                    ),
                ),
                (
                    "messages_by_hostname",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Hostname Bazında Mesajlar",
                    ),
                ),
                (
                    "avg_processing_time",
                    models.FloatField(
                        default=0, verbose_name="Ortalama İşlem Süresi (ms)"
                    ),
                ),
                (
                    "max_processing_time",
                    models.FloatField(
                        default=0, verbose_name="Maksimum İşlem Süresi (ms)"
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="Hata Sayısı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syslog_server.syslogserver",
                        verbose_name="Syslog Sunucu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syslog İstatistiği",
                "verbose_name_plural": "Syslog İstatistikleri",
                "ordering": ["-date", "-hour"],
                "unique_together": {("company", "server", "date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="SyslogMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility",
                    models.IntegerField(
                        choices=[
                            (0, "kernel messages"),
                            (1, "user-level messages"),
                            (2, "mail system"),
                            (3, "system daemons"),
                            (4, "security/authorization messages"),
                            (5, "messages generated internally by syslogd"),
                            (6, "line printer subsystem"),
                            (7, "network news subsystem"),
                            (8, "UUCP subsystem"),
                            (9, "clock daemon"),
                            (10, "security/authorization messages"),
                            (11, "FTP daemon"),
                            (12, "NTP subsystem"),
                            (13, "log audit"),
                            (14, "log alert"),
                            (15, "clock daemon"),
                            (16, "local use 0"),
                            (17, "local use 1"),
                            (18, "local use 2"),
                            (19, "local use 3"),
                            (20, "local use 4"),
                            (21, "local use 5"),
                            (22, "local use 6"),
                            (23, "local use 7"),
                        ],
                        verbose_name="Facility",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (0, "Emergency"),
                            (1, "Alert"),
                            (2, "Critical"),
                            (3, "Error"),
                            (4, "Warning"),
                            (5, "Notice"),
                            (6, "Informational"),
                            (7, "Debug"),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                ("severity", models.IntegerField(default=0, verbose_name="Severity")),
                ("timestamp", models.DateTimeField(verbose_name="Zaman Damgası")),
                ("hostname", models.CharField(max_length=255, verbose_name="Hostname")),
                (
                    "program",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Program"
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Process ID"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Kaynak IP"
                    ),
                ),
                (
                    "source_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak Port"
                    ),
                ),
                ("raw_message", models.TextField(blank=True, verbose_name="Ham Mesaj")),
                (
                    "is_parsed",
                    models.BooleanField(default=False, verbose_name="Parse Edildi"),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parse Edilmiş Veri"
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(default=False, verbose_name="Şüpheli"),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="Tehdit Seviyesi",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Alınma Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syslog_server.syslogserver",
                        verbose_name="Syslog Sunucu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syslog Mesajı",
                "verbose_name_plural": "Syslog Mesajları",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "received_at"],
                        name="syslog_serv_company_49e87b_idx",
                    ),
                    models.Index(
                        fields=["server", "received_at"],
                        name="syslog_serv_server__155c90_idx",
                    ),
                    models.Index(
                        fields=["facility", "priority"],
                        name="syslog_serv_facilit_5789cc_idx",
                    ),
                    models.Index(
                        fields=["hostname", "program"],
                        name="syslog_serv_hostnam_3a50dc_idx",
                    ),
                    models.Index(
                        fields=["is_suspicious", "threat_level"],
                        name="syslog_serv_is_susp_fbe4a3_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="syslog_serv_timesta_bcbd18_idx"
                    ),
                ],
            },
        ),
    ]
