# Generated by Django 4.2.7 on 2025-09-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0013_logkayit_cihaz_adi_logkayit_lokasyon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=200, verbose_name="İş Adı")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("RUNNING", "Çalışıyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                            ("CANCELLED", "İptal Edildi"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlama Zamanı"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Zamanı"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="Süre"),
                ),
                (
                    "total_records_processed",
                    models.BigIntegerField(
                        default=0, verbose_name="İşlenen Toplam Kayıt"
                    ),
                ),
                (
                    "records_archived",
                    models.BigIntegerField(default=0, verbose_name="Arşivlenen Kayıt"),
                ),
                (
                    "records_deleted",
                    models.BigIntegerField(default=0, verbose_name="Silinen Kayıt"),
                ),
                (
                    "records_failed",
                    models.BigIntegerField(default=0, verbose_name="Başarısız Kayıt"),
                ),
                (
                    "archive_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Arşiv Dosya Yolu"
                    ),
                ),
                (
                    "archive_file_size",
                    models.BigIntegerField(
                        default=0, verbose_name="Arşiv Dosya Boyutu (byte)"
                    ),
                ),
                (
                    "archive_file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Arşiv Dosya Hash"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Hata Detayları"
                    ),
                ),
                (
                    "job_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="İş Detayları"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Arşivleme İşi",
                "verbose_name_plural": "Arşivleme İşleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchivingStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Depolama Adı")),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Yerel Depolama"),
                            ("WORM", "WORM Disk"),
                            ("CLOUD", "Bulut Depolama"),
                            ("TAPE", "Tape Depolama"),
                            ("HYBRID", "Hibrit Depolama"),
                        ],
                        max_length=20,
                        verbose_name="Depolama Tipi",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=500, verbose_name="Depolama Yolu"),
                ),
                (
                    "total_capacity_gb",
                    models.IntegerField(verbose_name="Toplam Kapasite (GB)"),
                ),
                (
                    "used_capacity_gb",
                    models.IntegerField(verbose_name="Kullanılan Kapasite (GB)"),
                ),
                (
                    "available_capacity_gb",
                    models.IntegerField(verbose_name="Kullanılabilir Kapasite (GB)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("FULL", "Dolu"),
                            ("ERROR", "Hata"),
                            ("MAINTENANCE", "Bakım"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=True, verbose_name="Şifreli"),
                ),
                (
                    "is_compressed",
                    models.BooleanField(default=True, verbose_name="Sıkıştırılmış"),
                ),
                (
                    "is_worm",
                    models.BooleanField(default=False, verbose_name="WORM Disk"),
                ),
                (
                    "worm_append_only",
                    models.BooleanField(default=True, verbose_name="Sadece Ekleme"),
                ),
                (
                    "total_archives",
                    models.IntegerField(default=0, verbose_name="Toplam Arşiv"),
                ),
                (
                    "total_size_bytes",
                    models.BigIntegerField(
                        default=0, verbose_name="Toplam Boyut (byte)"
                    ),
                ),
                (
                    "last_archive_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Arşiv Tarihi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arşivleme Depolama",
                "verbose_name_plural": "Arşivleme Depolamaları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArchivingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Politika Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("LOG_RETENTION", "Log Saklama"),
                            ("TRAFFIC_RETENTION", "Trafik Saklama"),
                            ("SIGNATURE_RETENTION", "İmza Saklama"),
                            ("REPORT_RETENTION", "Rapor Saklama"),
                            ("GENERAL_RETENTION", "Genel Saklama"),
                        ],
                        max_length=20,
                        verbose_name="Politika Tipi",
                    ),
                ),
                (
                    "retention_period_years",
                    models.IntegerField(default=2, verbose_name="Saklama Süresi (Yıl)"),
                ),
                (
                    "retention_period_months",
                    models.IntegerField(default=0, verbose_name="Saklama Süresi (Ay)"),
                ),
                (
                    "retention_period_days",
                    models.IntegerField(default=0, verbose_name="Saklama Süresi (Gün)"),
                ),
                (
                    "archive_after_days",
                    models.IntegerField(
                        default=30,
                        help_text="Kaç gün sonra arşivlenecek",
                        verbose_name="Arşivleme Süresi (Gün)",
                    ),
                ),
                (
                    "compression_enabled",
                    models.BooleanField(default=True, verbose_name="Sıkıştırma Aktif"),
                ),
                (
                    "encryption_enabled",
                    models.BooleanField(default=True, verbose_name="Şifreleme Aktif"),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Yerel Depolama"),
                            ("WORM", "WORM Disk"),
                            ("CLOUD", "Bulut Depolama"),
                            ("TAPE", "Tape Depolama"),
                            ("HYBRID", "Hibrit Depolama"),
                        ],
                        default="LOCAL",
                        max_length=20,
                        verbose_name="Depolama Tipi",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Depolama Yolu"
                    ),
                ),
                (
                    "max_storage_size_gb",
                    models.IntegerField(
                        default=1000, verbose_name="Maksimum Depolama Boyutu (GB)"
                    ),
                ),
                (
                    "worm_enabled",
                    models.BooleanField(default=False, verbose_name="WORM Disk Aktif"),
                ),
                (
                    "worm_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="WORM Disk Yolu"
                    ),
                ),
                (
                    "worm_append_only",
                    models.BooleanField(default=True, verbose_name="Sadece Ekleme"),
                ),
                (
                    "auto_cleanup_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Otomatik Temizleme Aktif"
                    ),
                ),
                (
                    "cleanup_schedule",
                    models.CharField(
                        choices=[
                            ("DAILY", "Günlük"),
                            ("WEEKLY", "Haftalık"),
                            ("MONTHLY", "Aylık"),
                            ("QUARTERLY", "Üç Aylık"),
                        ],
                        default="WEEKLY",
                        max_length=50,
                        verbose_name="Temizleme Zamanlaması",
                    ),
                ),
                (
                    "notify_before_cleanup",
                    models.BooleanField(
                        default=True, verbose_name="Temizleme Öncesi Bildir"
                    ),
                ),
                (
                    "notify_after_cleanup",
                    models.BooleanField(
                        default=True, verbose_name="Temizleme Sonrası Bildir"
                    ),
                ),
                (
                    "notification_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış e-posta listesi",
                        verbose_name="Bildirim Alıcıları",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Çalıştırma"
                    ),
                ),
                (
                    "next_execution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sonraki Çalıştırma"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arşivleme Politikası",
                "verbose_name_plural": "Arşivleme Politikaları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArchivingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("ARCHIVE", "Arşivleme"),
                            ("CLEANUP", "Temizleme"),
                            ("VERIFY", "Doğrulama"),
                            ("RESTORE", "Geri Yükleme"),
                            ("ERROR", "Hata"),
                        ],
                        max_length=20,
                        verbose_name="Log Tipi",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaylar"),
                ),
                (
                    "records_affected",
                    models.BigIntegerField(default=0, verbose_name="Etkilenen Kayıt"),
                ),
                (
                    "storage_used_bytes",
                    models.BigIntegerField(
                        default=0, verbose_name="Kullanılan Depolama (byte)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="archiving_policy.archivingjob",
                        verbose_name="Arşivleme İşi",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="archiving_policy.archivingpolicy",
                        verbose_name="Arşivleme Politikası",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arşivleme Logu",
                "verbose_name_plural": "Arşivleme Logları",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="archivingjob",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="archiving_policy.archivingpolicy",
                verbose_name="Arşivleme Politikası",
            ),
        ),
    ]
