# Generated by Django 4.2.7 on 2025-09-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notification_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notification_system.notificationtemplate",
                verbose_name="Şablon",
            ),
        ),
    ]
