# Generated by Django 3.2.6 on 2025-06-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('ip_adresi', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('mac_adresi', models.CharField(max_length=17, verbose_name='MAC Adresi')),
                ('giris_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Giriş Zamanı')),
                ('sha256_hash', models.CharField(editable=False, max_length=64, verbose_name='SHA256 Hash')),
            ],
            options={
                'verbose_name': 'Log Kaydı',
                'verbose_name_plural': 'Log Kayıtları',
                'ordering': ['-giris_zamani'],
            },
        ),
    ]
