# Generated by Django 4.2.7 on 2025-09-04 20:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Firma",
                "verbose_name_plural": "Firmalar",
            },
        ),
        migrations.AlterModelOptions(
            name="logkayit",
            options={
                "ordering": ["-giris_zamani"],
                "verbose_name": "Log Kayıt",
                "verbose_name_plural": "Log Kayıtları",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="allow_foreigners",
            field=models.BooleanField(
                default=True, verbose_name="Yabancı Uyruklu İzni"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="kvkk_text",
            field=models.TextField(blank=True, default="", verbose_name="KVKK Metni"),
        ),
        migrations.AlterField(
            model_name="company",
            name="login_info_text",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Giriş Açıklaması"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Şirket Adı"),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="URL Kodu"),
        ),
        migrations.AlterField(
            model_name="company",
            name="theme_color",
            field=models.CharField(
                default="#007bff", max_length=7, verbose_name="Tema Rengi"
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="log_kayit.company",
                verbose_name="Firma",
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="is_suspicious",
            field=models.BooleanField(default=False, verbose_name="Şüpheli"),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="kimlik_turu",
            field=models.CharField(
                choices=[("tc", "T.C. Kimlik"), ("pasaport", "Pasaport")],
                default="tc",
                max_length=10,
                verbose_name="Kimlik Türü",
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="mac_adresi",
            field=models.CharField(
                blank=True, max_length=17, verbose_name="MAC Adresi"
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="pasaport_no",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Pasaport No"
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="pasaport_ulkesi",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Pasaport Ülkesi"
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="sha256_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="SHA256 Hash"
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="tc_no",
            field=models.CharField(
                blank=True,
                default="",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="T.C. Kimlik No 11 haneli olmalıdır.", regex="^\\d{11}$"
                    )
                ],
                verbose_name="T.C. Kimlik No",
            ),
        ),
        migrations.AlterField(
            model_name="logkayit",
            name="telefon",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Telefon"
            ),
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_view_dashboard",
                    models.BooleanField(
                        default=True, verbose_name="Dashboard Görüntüleme"
                    ),
                ),
                (
                    "can_export_data",
                    models.BooleanField(
                        default=False, verbose_name="Veri Dışa Aktarma"
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, verbose_name="Kullanıcı Yönetimi"
                    ),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(default=True, verbose_name="Rapor Görüntüleme"),
                ),
                (
                    "can_edit_company_settings",
                    models.BooleanField(default=False, verbose_name="Şirket Ayarları"),
                ),
                (
                    "access_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Erişim Başlangıç Saati"
                    ),
                ),
                (
                    "access_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Erişim Bitiş Saati"
                    ),
                ),
                (
                    "allowed_ips",
                    models.TextField(
                        blank=True,
                        help_text="Her satıra bir IP",
                        verbose_name="İzin Verilen IP Adresleri",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geçerlilik Tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="log_kayit.companyuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Yetkisi",
                "verbose_name_plural": "Kullanıcı Yetkileri",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Giriş Yapıldı"),
                            ("logout", "Çıkış Yapıldı"),
                            ("view_dashboard", "Dashboard Görüntülendi"),
                            ("export_data", "Veri Dışa Aktarıldı"),
                            ("manage_user", "Kullanıcı Yönetildi"),
                            ("edit_settings", "Ayarlar Düzenlendi"),
                            ("view_report", "Rapor Görüntülendi"),
                            ("unauthorized_access", "Yetkisiz Erişim Denemesi"),
                        ],
                        max_length=50,
                        verbose_name="İşlem",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("details", models.TextField(blank=True, verbose_name="Detaylar")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="log_kayit.companyuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Aktivite Logu",
                "verbose_name_plural": "Kullanıcı Aktivite Logları",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_login_attempts",
                    models.IntegerField(
                        default=3, verbose_name="Maksimum Giriş Denemesi"
                    ),
                ),
                (
                    "session_timeout",
                    models.IntegerField(
                        default=60, verbose_name="Oturum Zaman Aşımı (dakika)"
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False, verbose_name="İki Faktörlü Doğrulama"
                    ),
                ),
                (
                    "auto_cleanup_days",
                    models.IntegerField(
                        default=730, verbose_name="Otomatik Temizlik (gün)"
                    ),
                ),
                (
                    "backup_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Yedekleme Sıklığı",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="E-posta Bildirimleri"
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Bildirim E-postası"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="log_kayit.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket Ayarı",
                "verbose_name_plural": "Şirket Ayarları",
            },
        ),
    ]
