# Generated by Django 4.2.7 on 2025-09-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0012_alter_logkayit_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Rapor Başlığı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="Dönem Başlangıcı")),
                ("period_end", models.DateTimeField(verbose_name="Dönem Bitişi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("generating", "Oluşturuluyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Dosya Yolu"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Dosya Boyutu"
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="Toplam Kayıt"),
                ),
                (
                    "suspicious_records",
                    models.IntegerField(default=0, verbose_name="Şüpheli Kayıt"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="Hata Sayısı"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlama Zamanı"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Zamanı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oluşturulan Rapor",
                "verbose_name_plural": "Oluşturulan Raporlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şablon Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük Rapor"),
                            ("weekly", "Haftalık Rapor"),
                            ("monthly", "Aylık Rapor"),
                            ("quarterly", "Çeyrek Rapor"),
                            ("yearly", "Yıllık Rapor"),
                            ("custom", "Özel Rapor"),
                            ("compliance", "Uyumluluk Raporu"),
                            ("security", "Güvenlik Raporu"),
                            ("performance", "Performans Raporu"),
                        ],
                        max_length=20,
                        verbose_name="Şablon Tipi",
                    ),
                ),
                (
                    "include_user_logs",
                    models.BooleanField(default=True, verbose_name="Kullanıcı Logları"),
                ),
                (
                    "include_syslog_data",
                    models.BooleanField(default=True, verbose_name="Syslog Verileri"),
                ),
                (
                    "include_mirror_traffic",
                    models.BooleanField(default=True, verbose_name="Mirror Trafik"),
                ),
                (
                    "include_timestamp_data",
                    models.BooleanField(
                        default=True, verbose_name="Zaman Damgası Verileri"
                    ),
                ),
                (
                    "include_security_alerts",
                    models.BooleanField(
                        default=True, verbose_name="Güvenlik Uyarıları"
                    ),
                ),
                (
                    "date_range_days",
                    models.IntegerField(default=30, verbose_name="Tarih Aralığı (Gün)"),
                ),
                (
                    "include_suspicious_only",
                    models.BooleanField(
                        default=False, verbose_name="Sadece Şüpheli Kayıtlar"
                    ),
                ),
                (
                    "min_severity_level",
                    models.IntegerField(
                        default=0, verbose_name="Minimum Önem Seviyesi"
                    ),
                ),
                (
                    "include_charts",
                    models.BooleanField(default=True, verbose_name="Grafikler Dahil"),
                ),
                (
                    "include_statistics",
                    models.BooleanField(
                        default=True, verbose_name="İstatistikler Dahil"
                    ),
                ),
                (
                    "include_summary",
                    models.BooleanField(default=True, verbose_name="Özet Dahil"),
                ),
                (
                    "include_details",
                    models.BooleanField(default=True, verbose_name="Detaylar Dahil"),
                ),
                (
                    "auto_generate",
                    models.BooleanField(default=False, verbose_name="Otomatik Oluştur"),
                ),
                (
                    "generation_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Oluşturma Sıklığı",
                    ),
                ),
                (
                    "generation_time",
                    models.TimeField(default="09:00", verbose_name="Oluşturma Saati"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapor Şablonu",
                "verbose_name_plural": "Rapor Şablonları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Zamanlama Adı"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                            ("quarterly", "Çeyrek"),
                            ("yearly", "Yıllık"),
                        ],
                        max_length=20,
                        verbose_name="Sıklık",
                    ),
                ),
                (
                    "run_time",
                    models.TimeField(default="09:00", verbose_name="Çalışma Saati"),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Pazartesi"),
                            (1, "Salı"),
                            (2, "Çarşamba"),
                            (3, "Perşembe"),
                            (4, "Cuma"),
                            (5, "Cumartesi"),
                            (6, "Pazar"),
                        ],
                        null=True,
                        verbose_name="Haftanın Günü",
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ayın Günü"
                    ),
                ),
                (
                    "notify_on_success",
                    models.BooleanField(default=True, verbose_name="Başarıda Bildir"),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(
                        default=True, verbose_name="Hata Durumunda Bildir"
                    ),
                ),
                (
                    "notification_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış email listesi",
                        verbose_name="Bildirim Alıcıları",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Çalışma"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sonraki Çalışma"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_reporting.reporttemplate",
                        verbose_name="Şablon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapor Zamanlaması",
                "verbose_name_plural": "Rapor Zamanlamaları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("ftp", "FTP"),
                            ("sftp", "SFTP"),
                            ("webhook", "Webhook"),
                            ("api", "API"),
                            ("download", "İndirme Linki"),
                        ],
                        max_length=20,
                        verbose_name="Dağıtım Tipi",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Alıcı E-posta"
                    ),
                ),
                (
                    "ftp_host",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="FTP Host"
                    ),
                ),
                (
                    "ftp_username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="FTP Kullanıcı"
                    ),
                ),
                (
                    "ftp_password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="FTP Şifre"
                    ),
                ),
                (
                    "ftp_path",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="FTP Yolu"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook URL"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "last_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Gönderim"
                    ),
                ),
                (
                    "sent_count",
                    models.IntegerField(default=0, verbose_name="Gönderim Sayısı"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_reporting.generatedreport",
                        verbose_name="Rapor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapor Dağıtımı",
                "verbose_name_plural": "Rapor Dağıtımları",
                "ordering": ["distribution_type"],
            },
        ),
        migrations.CreateModel(
            name="ReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(max_length=50, verbose_name="Veri Tipi"),
                ),
                (
                    "data_key",
                    models.CharField(max_length=100, verbose_name="Veri Anahtarı"),
                ),
                ("data_value", models.JSONField(verbose_name="Veri Değeri")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_reporting.generatedreport",
                        verbose_name="Rapor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapor Verisi",
                "verbose_name_plural": "Rapor Verileri",
                "ordering": ["data_type", "data_key"],
            },
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="advanced_reporting.reportschedule",
                verbose_name="Zamanlama",
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advanced_reporting.reporttemplate",
                verbose_name="Şablon",
            ),
        ),
    ]
