# Generated by Django 4.2.7 on 2025-09-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("log_kayit", "0012_alter_logkayit_company"),
        ("advanced_reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedreport",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="log_kayit.company",
                verbose_name="Şirket",
            ),
        ),
        migrations.AddField(
            model_name="reportdata",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="log_kayit.company",
                verbose_name="Şirket",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="log_kayit.company",
                verbose_name="Şirket",
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="log_kayit.company",
                verbose_name="Şirket",
            ),
        ),
    ]
