# Generated by Django 4.2.7 on 2025-09-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "advanced_reporting",
            "0002_generatedreport_company_reportdata_company_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="filters",
            field=models.JSONField(blank=True, default=dict, verbose_name="Filtreler"),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="report_format",
            field=models.CharField(
                default="pdf", max_length=10, verbose_name="Rapor Formatı"
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="report_type",
            field=models.CharField(
                default="user_activity", max_length=50, verbose_name="Rapor Türü"
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="template_config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Şablon Konfigürasyonu"
            ),
        ),
    ]
