# Generated by Django 4.2.7 on 2025-09-09 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0013_logkayit_cihaz_adi_logkayit_lokasyon_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Günlük"),
                            ("WEEKLY", "Haftalık"),
                            ("MONTHLY", "Aylık"),
                            ("CUSTOM", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Türü",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateTimeField(verbose_name="Bitiş Tarihi")),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                (
                    "total_events",
                    models.PositiveIntegerField(default=0, verbose_name="Toplam Olay"),
                ),
                (
                    "critical_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kritik Olaylar"
                    ),
                ),
                (
                    "high_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Yüksek Öncelikli Olaylar"
                    ),
                ),
                (
                    "failed_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Başarısız Olaylar"
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audit_reports/",
                        verbose_name="Rapor Dosyası",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Raporu",
                "verbose_name_plural": "Audit Log Raporları",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Oluşturma"),
                            ("READ", "Okuma"),
                            ("UPDATE", "Güncelleme"),
                            ("DELETE", "Silme"),
                            ("LOGIN", "Giriş"),
                            ("LOGOUT", "Çıkış"),
                            ("PASSWORD_CHANGE", "Şifre Değiştirme"),
                            ("PERMISSION_CHANGE", "Yetki Değiştirme"),
                            ("EXPORT", "Dışa Aktarma"),
                            ("IMPORT", "İçe Aktarma"),
                            ("API_ACCESS", "API Erişimi"),
                            ("SECURITY_EVENT", "Güvenlik Olayı"),
                        ],
                        max_length=50,
                        verbose_name="İşlem",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="Önem Derecesi",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Saklama Süresi (Gün)"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Konfigürasyonu",
                "verbose_name_plural": "Audit Log Konfigürasyonları",
                "unique_together": {("company", "action")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Oluşturma"),
                            ("READ", "Okuma"),
                            ("UPDATE", "Güncelleme"),
                            ("DELETE", "Silme"),
                            ("LOGIN", "Giriş"),
                            ("LOGOUT", "Çıkış"),
                            ("PASSWORD_CHANGE", "Şifre Değiştirme"),
                            ("PERMISSION_CHANGE", "Yetki Değiştirme"),
                            ("EXPORT", "Dışa Aktarma"),
                            ("IMPORT", "İçe Aktarma"),
                            ("API_ACCESS", "API Erişimi"),
                            ("SECURITY_EVENT", "Güvenlik Olayı"),
                        ],
                        max_length=50,
                        verbose_name="İşlem",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="Önem Derecesi",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=100, verbose_name="Kaynak Türü"),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kaynak ID"
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Kaynak Adı"
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaylar"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Zaman"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True, verbose_name="Başarılı")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logları",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_loggi_user_id_0157bd_idx",
                    ),
                    models.Index(
                        fields=["company", "timestamp"],
                        name="audit_loggi_company_d57c20_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_loggi_action_1350d5_idx",
                    ),
                    models.Index(
                        fields=["severity", "timestamp"],
                        name="audit_loggi_severit_4b8d51_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="audit_loggi_ip_addr_8a45d4_idx",
                    ),
                ],
            },
        ),
    ]
