# Generated by Django 4.2.7 on 2025-09-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0001_initial"),
    ]

    operations = []
