# Generated by Django 4.2.7 on 2025-09-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0003_auto_20250910_0235"),
    ]

    operations = []
