# Generated by Django 4.2.7 on 2025-09-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuthSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enforce_for_admins",
                    models.BooleanField(
                        default=True, verbose_name="Admin'ler için Zorunlu"
                    ),
                ),
                (
                    "enforce_for_all",
                    models.BooleanField(
                        default=False, verbose_name="Tüm Kullanıcılar için Zorunlu"
                    ),
                ),
                (
                    "backup_tokens_count",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Yedek Token Sayısı"
                    ),
                ),
                (
                    "token_validity_window",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Token Geçerlilik Penceresi"
                    ),
                ),
                (
                    "max_failed_attempts",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Maksimum Başarısız Deneme"
                    ),
                ),
                (
                    "lockout_duration",
                    models.PositiveIntegerField(
                        default=300, verbose_name="Kilitleme Süresi (Saniye)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA Ayarları",
                "verbose_name_plural": "2FA Ayarları",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ENABLE", "Aktif Edildi"),
                            ("DISABLE", "Pasif Edildi"),
                            ("LOGIN_SUCCESS", "Giriş Başarılı"),
                            ("LOGIN_FAILED", "Giriş Başarısız"),
                            ("BACKUP_USED", "Yedek Token Kullanıldı"),
                            ("BACKUP_GENERATED", "Yedek Tokenlar Oluşturuldu"),
                        ],
                        max_length=20,
                        verbose_name="İşlem",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Başarılı")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaylar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA Log",
                "verbose_name_plural": "2FA Logları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(max_length=32, verbose_name="Secret Key"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Aktif"),
                ),
                (
                    "backup_tokens",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Yedek Tokenlar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Two Factor Auth",
                "verbose_name_plural": "Two Factor Auth",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuthAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "failed_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Başarısız Denemeler"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kilitli Olana Kadar"
                    ),
                ),
                (
                    "last_attempt",
                    models.DateTimeField(auto_now=True, verbose_name="Son Deneme"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA Deneme",
                "verbose_name_plural": "2FA Denemeleri",
                "unique_together": {("user", "ip_address")},
            },
        ),
    ]
