# Generated by Django 4.2.7 on 2025-09-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("device_integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                        verbose_name="Seviye",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "source",
                    models.CharField(
                        default="system", max_length=100, verbose_name="Kaynak"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="Meta Veri")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device_integrations.device",
                        verbose_name="Cihaz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cihaz Logu",
                "verbose_name_plural": "Cihaz Logları",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "level", "timestamp"],
                        name="device_inte_device__ae1de6_idx",
                    )
                ],
            },
        ),
    ]
