# Generated by Django 4.2.7 on 2025-09-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0012_alter_logkayit_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimestampAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Otorite Adı")),
                (
                    "authority_type",
                    models.CharField(
                        choices=[
                            ("TUBITAK", "TÜBİTAK"),
                            ("TURKTRUST", "TurkTrust"),
                            ("CUSTOM", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Otorite Tipi",
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(blank=True, verbose_name="API Endpoint"),
                ),
                (
                    "certificate_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Sertifika Yolu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API Anahtarı"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kullanıcı Adı"
                    ),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=255, verbose_name="Şifre"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaman Damgası Otoritesi",
                "verbose_name_plural": "Zaman Damgası Otoriteleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimestampConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_sign",
                    models.BooleanField(default=True, verbose_name="Otomatik İmzalama"),
                ),
                (
                    "sign_interval",
                    models.IntegerField(
                        default=60,
                        help_text="Kaç dakikada bir imzalama yapılacak",
                        verbose_name="İmzalama Aralığı (dakika)",
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=100,
                        help_text="Bir seferde kaç kayıt imzalanacak",
                        verbose_name="Toplu İmzalama Boyutu",
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, verbose_name="Maksimum Deneme"),
                ),
                (
                    "retry_delay",
                    models.IntegerField(
                        default=300, verbose_name="Deneme Gecikmesi (saniye)"
                    ),
                ),
                (
                    "notify_on_success",
                    models.BooleanField(default=True, verbose_name="Başarı Bildirimi"),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(default=True, verbose_name="Hata Bildirimi"),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Bildirim E-postası"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timestamp_signing.timestampauthority",
                        verbose_name="Varsayılan Otorite",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timestamp_config",
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaman Damgası Konfigürasyonu",
                "verbose_name_plural": "Zaman Damgası Konfigürasyonları",
            },
        ),
        migrations.CreateModel(
            name="TimestampSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_data",
                    models.TextField(
                        help_text="RFC 3161 uyumlu imza verisi",
                        verbose_name="İmza Verisi",
                    ),
                ),
                (
                    "timestamp_token",
                    models.TextField(blank=True, verbose_name="Zaman Damgası Token"),
                ),
                (
                    "certificate_chain",
                    models.TextField(blank=True, verbose_name="Sertifika Zinciri"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("SIGNED", "İmzalandı"),
                            ("FAILED", "Başarısız"),
                            ("VERIFIED", "Doğrulandı"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İmzalama Zamanı"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Doğrulama Zamanı"
                    ),
                ),
                (
                    "hash_algorithm",
                    models.CharField(
                        default="SHA256", max_length=20, verbose_name="Hash Algoritması"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Seri Numarası"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timestamp_signing.timestampauthority",
                        verbose_name="Otorite",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timestamp_signatures",
                        to="log_kayit.logkayit",
                        verbose_name="Log Kaydı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaman Damgası İmzası",
                "verbose_name_plural": "Zaman Damgası İmzaları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["log_entry", "status"],
                        name="timestamp_s_log_ent_991578_idx",
                    ),
                    models.Index(
                        fields=["company", "created_at"],
                        name="timestamp_s_company_068c8c_idx",
                    ),
                    models.Index(
                        fields=["status", "signed_at"],
                        name="timestamp_s_status_829ef9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TimestampLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("SIGN", "İmzalama"),
                            ("VERIFY", "Doğrulama"),
                            ("ERROR", "Hata"),
                            ("BATCH_SIGN", "Toplu İmzalama"),
                        ],
                        max_length=20,
                        verbose_name="Log Tipi",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaylar"),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="İşlenen Kayıt Sayısı"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="Başarılı İşlem"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="Başarısız İşlem"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaman Damgası Logu",
                "verbose_name_plural": "Zaman Damgası Logları",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["company", "timestamp"],
                        name="timestamp_s_company_a12405_idx",
                    ),
                    models.Index(
                        fields=["log_type", "timestamp"],
                        name="timestamp_s_log_typ_048b48_idx",
                    ),
                ],
            },
        ),
    ]
