# Generated by Django 4.2.7 on 2025-09-02 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("THREAT_DETECTED", "Tehdit Tespit Edildi"),
                            ("ANOMALY_DETECTED", "Anomali Tespit Edildi"),
                            ("POLICY_VIOLATION", "Politika İhlali"),
                            ("SYSTEM_COMPROMISE", "Sistem Ele Geçirildi"),
                            ("DATA_BREACH", "Veri İhlali"),
                            ("NETWORK_INTRUSION", "Ağ İhlali"),
                            ("USER_BEHAVIOR", "Kullanıcı Davranışı"),
                            ("PERFORMANCE_ISSUE", "Performans Sorunu"),
                            ("COMPLIANCE_ALERT", "Uyumluluk Uyarısı"),
                        ],
                        max_length=20,
                        verbose_name="Uyarı Tipi",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "Yüksek"),
                            ("URGENT", "Acil"),
                            ("IMMEDIATE", "Anında"),
                        ],
                        default="NORMAL",
                        max_length=15,
                        verbose_name="Öncelik",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("details", models.JSONField(default=dict, verbose_name="Detaylar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Zamanı"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kabul Edilme Zamanı"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(default=False, verbose_name="Kabul Edildi"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Çözüldü"),
                ),
                (
                    "is_escalated",
                    models.BooleanField(default=False, verbose_name="Yükseltildi"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kabul Eden",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Uyarısı",
                "verbose_name_plural": "Güvenlik Uyarıları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreatIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intel_type",
                    models.CharField(
                        choices=[
                            ("IP_REPUTATION", "IP İtibarı"),
                            ("DOMAIN_REPUTATION", "Domain İtibarı"),
                            ("MALWARE_SIGNATURE", "Zararlı Yazılım İmzası"),
                            ("ATTACK_PATTERN", "Saldırı Paterni"),
                            ("VULNERABILITY", "Güvenlik Açığı"),
                            ("THREAT_ACTOR", "Tehdit Aktörü"),
                            ("CAMPAIGN", "Kampanya"),
                            ("INDICATOR", "Gösterge"),
                        ],
                        max_length=20,
                        verbose_name="İstihbarat Tipi",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="İsim")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("value", models.CharField(max_length=500, verbose_name="Değer")),
                (
                    "confidence",
                    models.IntegerField(default=0, verbose_name="Güven (%)"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                            ("EMERGENCY", "Acil"),
                        ],
                        max_length=15,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                ("source", models.CharField(max_length=100, verbose_name="Kaynak")),
                (
                    "first_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İlk Görülme"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Son Görülme"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Etiketler"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tehdit İstihbaratı",
                "verbose_name_plural": "Tehdit İstihbaratları",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="SecurityThreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threat_type",
                    models.CharField(
                        choices=[
                            ("MALWARE", "Zararlı Yazılım"),
                            ("PHISHING", "Oltalama Saldırısı"),
                            ("DDOS", "DDoS Saldırısı"),
                            ("BRUTE_FORCE", "Brute Force"),
                            ("SQL_INJECTION", "SQL Enjeksiyonu"),
                            ("XSS", "Cross-Site Scripting"),
                            ("MAN_IN_MIDDLE", "Ortadaki Adam Saldırısı"),
                            ("PORT_SCAN", "Port Tarama"),
                            ("UNAUTHORIZED_ACCESS", "Yetkisiz Erişim"),
                            ("DATA_EXFILTRATION", "Veri Sızıntısı"),
                            ("RANSOMWARE", "Fidye Yazılımı"),
                            ("ZERO_DAY", "Sıfır Gün Açığı"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Tehdit Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                            ("EMERGENCY", "Acil"),
                        ],
                        max_length=15,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "Tespit Edildi"),
                            ("ANALYZING", "Analiz Ediliyor"),
                            ("CONFIRMED", "Doğrulandı"),
                            ("MITIGATED", "Azaltıldı"),
                            ("RESOLVED", "Çözüldü"),
                            ("FALSE_POSITIVE", "Yanlış Pozitif"),
                        ],
                        default="DETECTED",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Kaynak IP"
                    ),
                ),
                (
                    "destination_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Hedef IP"
                    ),
                ),
                (
                    "source_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak Port"
                    ),
                ),
                (
                    "destination_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hedef Port"
                    ),
                ),
                (
                    "detection_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tespit Zamanı"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "resolved_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "confidence_score",
                    models.IntegerField(default=0, verbose_name="Güven Skoru (%)"),
                ),
                (
                    "false_positive_probability",
                    models.IntegerField(
                        default=0, verbose_name="Yanlış Pozitif Olasılığı (%)"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Etiketler"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan Kişi",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Tehdidi",
                "verbose_name_plural": "Güvenlik Tehditleri",
                "ordering": ["-detection_time"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("BREACH", "Veri İhlali"),
                            ("INTRUSION", "Sistem İhlali"),
                            ("MALWARE", "Zararlı Yazılım"),
                            ("PHISHING", "Oltalama"),
                            ("DDOS", "DDoS Saldırısı"),
                            ("INSIDER_THREAT", "İç Tehdit"),
                            ("PHYSICAL_SECURITY", "Fiziksel Güvenlik"),
                            ("COMPLIANCE_VIOLATION", "Uyumluluk İhlali"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Olay Tipi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Açık"),
                            ("INVESTIGATING", "Araştırılıyor"),
                            ("CONTAINED", "Sınırlandırıldı"),
                            ("RESOLVED", "Çözüldü"),
                            ("CLOSED", "Kapatıldı"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "discovered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Keşfedilme Zamanı"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlama Zamanı"
                    ),
                ),
                (
                    "contained_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sınırlandırılma Zamanı"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                            ("EMERGENCY", "Acil"),
                        ],
                        max_length=15,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                            ("EMERGENCY", "Acil"),
                        ],
                        max_length=15,
                        verbose_name="Etki Seviyesi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan Kişi",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "related_alerts",
                    models.ManyToManyField(
                        blank=True,
                        to="security_alerts.securityalert",
                        verbose_name="İlişkili Uyarılar",
                    ),
                ),
                (
                    "related_threats",
                    models.ManyToManyField(
                        blank=True,
                        to="security_alerts.securitythreat",
                        verbose_name="İlişkili Tehditler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Olayı",
                "verbose_name_plural": "Güvenlik Olayları",
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.AddField(
            model_name="securityalert",
            name="related_threat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="security_alerts.securitythreat",
                verbose_name="İlişkili Tehdit",
            ),
        ),
        migrations.AddField(
            model_name="securityalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Çözen",
            ),
        ),
        migrations.CreateModel(
            name="SecurityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "total_threats",
                    models.IntegerField(default=0, verbose_name="Toplam Tehdit"),
                ),
                (
                    "critical_threats",
                    models.IntegerField(default=0, verbose_name="Kritik Tehdit"),
                ),
                (
                    "high_threats",
                    models.IntegerField(default=0, verbose_name="Yüksek Tehdit"),
                ),
                (
                    "medium_threats",
                    models.IntegerField(default=0, verbose_name="Orta Tehdit"),
                ),
                (
                    "low_threats",
                    models.IntegerField(default=0, verbose_name="Düşük Tehdit"),
                ),
                (
                    "total_alerts",
                    models.IntegerField(default=0, verbose_name="Toplam Uyarı"),
                ),
                (
                    "acknowledged_alerts",
                    models.IntegerField(default=0, verbose_name="Kabul Edilen Uyarı"),
                ),
                (
                    "resolved_alerts",
                    models.IntegerField(default=0, verbose_name="Çözülen Uyarı"),
                ),
                (
                    "total_incidents",
                    models.IntegerField(default=0, verbose_name="Toplam Olay"),
                ),
                (
                    "open_incidents",
                    models.IntegerField(default=0, verbose_name="Açık Olay"),
                ),
                (
                    "resolved_incidents",
                    models.IntegerField(default=0, verbose_name="Çözülen Olay"),
                ),
                (
                    "mean_time_to_detect",
                    models.FloatField(
                        default=0.0, verbose_name="Ortalama Tespit Süresi (Saat)"
                    ),
                ),
                (
                    "mean_time_to_resolve",
                    models.FloatField(
                        default=0.0, verbose_name="Ortalama Çözüm Süresi (Saat)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Metriği",
                "verbose_name_plural": "Güvenlik Metrikleri",
                "ordering": ["-date"],
                "unique_together": {("company", "date")},
            },
        ),
    ]
