# Generated by Django 4.2.7 on 2025-09-08 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("log_kayit", "0013_logkayit_cihaz_adi_logkayit_lokasyon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("COURT_ORDER", "Mahkeme Kararı"),
                            ("BTK_REQUEST", "BTK Talebi"),
                            ("LEGAL_REQUEST", "Yasal Talep"),
                            ("AUDIT_REQUEST", "Denetim Talebi"),
                            ("COMPLIANCE_CHECK", "Uyumluluk Kontrolü"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Taslak"),
                            ("PENDING_APPROVAL", "Onay Bekliyor"),
                            ("APPROVED", "Onaylandı"),
                            ("GENERATED", "Oluşturuldu"),
                            ("DELIVERED", "Teslim Edildi"),
                            ("REJECTED", "Reddedildi"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "Yüksek"),
                            ("URGENT", "Acil"),
                            ("CRITICAL", "Kritik"),
                        ],
                        default="NORMAL",
                        max_length=15,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Talep Numarası"
                    ),
                ),
                ("request_date", models.DateTimeField(verbose_name="Talep Tarihi")),
                (
                    "requester_name",
                    models.CharField(max_length=200, verbose_name="Talep Eden"),
                ),
                (
                    "requester_authority",
                    models.CharField(max_length=200, verbose_name="Talep Eden Kurum"),
                ),
                (
                    "requester_contact",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="İletişim Bilgileri"
                    ),
                ),
                (
                    "report_title",
                    models.CharField(max_length=300, verbose_name="Rapor Başlığı"),
                ),
                (
                    "report_description",
                    models.TextField(verbose_name="Rapor Açıklaması"),
                ),
                (
                    "requested_data_period",
                    models.CharField(
                        max_length=100, verbose_name="Talep Edilen Veri Dönemi"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateTimeField(verbose_name="Bitiş Tarihi")),
                (
                    "filter_criteria",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Filtreleme Kriterleri"
                    ),
                ),
                (
                    "include_logs",
                    models.BooleanField(
                        default=True, verbose_name="Log Kayıtları Dahil"
                    ),
                ),
                (
                    "include_traffic",
                    models.BooleanField(
                        default=True, verbose_name="Trafik Verileri Dahil"
                    ),
                ),
                (
                    "include_signatures",
                    models.BooleanField(default=True, verbose_name="İmzalar Dahil"),
                ),
                (
                    "include_verification",
                    models.BooleanField(
                        default=True, verbose_name="Doğrulama Sonuçları Dahil"
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("CSV", "CSV"),
                            ("EXCEL", "Excel"),
                            ("JSON", "JSON"),
                            ("XML", "XML"),
                        ],
                        default="PDF",
                        max_length=10,
                        verbose_name="Rapor Formatı",
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evidence_reports/",
                        verbose_name="Oluşturulan Dosya",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, verbose_name="Dosya Boyutu (byte)"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Dosya Hash"
                    ),
                ),
                (
                    "total_records",
                    models.BigIntegerField(default=0, verbose_name="Toplam Kayıt"),
                ),
                (
                    "total_logs",
                    models.BigIntegerField(default=0, verbose_name="Toplam Log"),
                ),
                (
                    "total_traffic_records",
                    models.BigIntegerField(
                        default=0, verbose_name="Toplam Trafik Kaydı"
                    ),
                ),
                (
                    "total_signatures",
                    models.IntegerField(default=0, verbose_name="Toplam İmza"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Onay Tarihi"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Teslim Tarihi"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Teslim Tarihi"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="İç Notlar"),
                ),
                (
                    "external_notes",
                    models.TextField(blank=True, verbose_name="Dış Notlar"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_evidence_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_evidence_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_evidence_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Sistem",
                    ),
                ),
            ],
            options={
                "verbose_name": "İbraz Raporu",
                "verbose_name_plural": "İbraz Raporları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Şablon Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("COURT_ORDER", "Mahkeme Kararı"),
                            ("BTK_REQUEST", "BTK Talebi"),
                            ("LEGAL_REQUEST", "Yasal Talep"),
                            ("AUDIT_REQUEST", "Denetim Talebi"),
                            ("COMPLIANCE_CHECK", "Uyumluluk Kontrolü"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                ("template_content", models.TextField(verbose_name="Şablon İçeriği")),
                (
                    "default_format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("CSV", "CSV"), ("EXCEL", "Excel")],
                        default="PDF",
                        max_length=10,
                        verbose_name="Varsayılan Format",
                    ),
                ),
                (
                    "default_include_logs",
                    models.BooleanField(
                        default=True, verbose_name="Varsayılan Log Dahil"
                    ),
                ),
                (
                    "default_include_traffic",
                    models.BooleanField(
                        default=True, verbose_name="Varsayılan Trafik Dahil"
                    ),
                ),
                (
                    "default_include_signatures",
                    models.BooleanField(
                        default=True, verbose_name="Varsayılan İmza Dahil"
                    ),
                ),
                (
                    "default_include_verification",
                    models.BooleanField(
                        default=True, verbose_name="Varsayılan Doğrulama Dahil"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "İbraz Raporu Şablonu",
                "verbose_name_plural": "İbraz Raporu Şablonları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Oluşturuldu"),
                            ("UPDATED", "Güncellendi"),
                            ("APPROVED", "Onaylandı"),
                            ("REJECTED", "Reddedildi"),
                            ("GENERATED", "Oluşturuldu"),
                            ("DELIVERED", "Teslim Edildi"),
                            ("DOWNLOADED", "İndirildi"),
                            ("VIEWED", "Görüntülendi"),
                        ],
                        max_length=20,
                        verbose_name="İşlem",
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaylar"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="evidence_reports.evidencereport",
                        verbose_name="İbraz Raporu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İbraz Raporu Logu",
                "verbose_name_plural": "İbraz Raporu Logları",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceReportAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Görüntüleme"),
                            ("DOWNLOAD", "İndirme"),
                            ("PRINT", "Yazdırma"),
                            ("EXPORT", "Dışa Aktarma"),
                        ],
                        max_length=20,
                        verbose_name="Erişim Tipi",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Oturum ID"
                    ),
                ),
                (
                    "access_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Erişim Süresi"
                    ),
                ),
                (
                    "pages_viewed",
                    models.IntegerField(default=0, verbose_name="Görüntülenen Sayfa"),
                ),
                (
                    "data_accessed",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Erişilen Veri"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Erişim Zamanı"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="evidence_reports.evidencereport",
                        verbose_name="İbraz Raporu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İbraz Raporu Erişim Kaydı",
                "verbose_name_plural": "İbraz Raporu Erişim Kayıtları",
                "ordering": ["-timestamp"],
            },
        ),
    ]
