# Generated by Django 4.2.7 on 2025-09-03 21:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Cihaz Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "port",
                    models.IntegerField(
                        default=22,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="Port",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        default="ssh", max_length=20, verbose_name="Protokol"
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(default=dict, verbose_name="Kimlik Bilgileri"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Bakım"),
                            ("error", "Hata"),
                            ("unknown", "Bilinmiyor"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Son Görülme"
                    ),
                ),
                (
                    "is_monitored",
                    models.BooleanField(default=True, verbose_name="İzleniyor"),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("mikrotik", "MikroTik"),
                            ("vmware", "VMware"),
                            ("proxmox", "Proxmox"),
                            ("cisco", "Cisco"),
                            ("custom", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Entegrasyon Tipi",
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(blank=True, verbose_name="API Endpoint"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API Anahtarı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cihaz",
                "verbose_name_plural": "Cihazlar",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Cihaz Adı")),
                ("vendor", models.CharField(max_length=100, verbose_name="Üretici")),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("router", "Router"),
                            ("switch", "Switch"),
                            ("firewall", "Firewall"),
                            ("server", "Server"),
                            ("vm", "Virtual Machine"),
                            ("container", "Container"),
                            ("storage", "Storage"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "capabilities",
                    models.JSONField(default=dict, verbose_name="Özellikler"),
                ),
                (
                    "supported_protocols",
                    models.JSONField(
                        default=list, verbose_name="Desteklenen Protokoller"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cihaz Tipi",
                "verbose_name_plural": "Cihaz Tipleri",
                "ordering": ["vendor", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Bakım"),
                            ("error", "Hata"),
                            ("unknown", "Bilinmiyor"),
                        ],
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "cpu_usage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="CPU Kullanımı (%)",
                    ),
                ),
                (
                    "memory_usage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="RAM Kullanımı (%)",
                    ),
                ),
                (
                    "disk_usage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Disk Kullanımı (%)",
                    ),
                ),
                (
                    "bandwidth_in",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Gelen Bandwidth (bytes)"
                    ),
                ),
                (
                    "bandwidth_out",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Giden Bandwidth (bytes)"
                    ),
                ),
                (
                    "active_connections",
                    models.IntegerField(default=0, verbose_name="Aktif Bağlantılar"),
                ),
                ("warnings", models.JSONField(default=list, verbose_name="Uyarılar")),
                ("errors", models.JSONField(default=list, verbose_name="Hatalar")),
                (
                    "critical_alerts",
                    models.JSONField(default=list, verbose_name="Kritik Uyarılar"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device_integrations.device",
                        verbose_name="Cihaz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cihaz Durumu",
                "verbose_name_plural": "Cihaz Durumları",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="device_integrations.devicetype",
                verbose_name="Cihaz Tipi",
            ),
        ),
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("memory", "Memory"),
                            ("disk", "Disk"),
                            ("network", "Network"),
                            ("temperature", "Temperature"),
                            ("power", "Power"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                        verbose_name="Metrik Tipi",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Değer"
                    ),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="Birim")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                ("is_alert", models.BooleanField(default=False, verbose_name="Uyarı")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device_integrations.device",
                        verbose_name="Cihaz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cihaz Metriği",
                "verbose_name_plural": "Cihaz Metrikleri",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "metric_type", "timestamp"],
                        name="device_inte_device__ec82d1_idx",
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("ip_address", "company")},
        ),
    ]
