# Generated by Django 4.2.7 on 2025-09-02 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kural Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ALLOW", "İzin Ver"),
                            ("DENY", "Reddet"),
                            ("DROP", "Düşür"),
                            ("REJECT", "Reddet ve Bildir"),
                        ],
                        max_length=10,
                        verbose_name="Kural Tipi",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("TCP", "TCP"),
                            ("UDP", "UDP"),
                            ("ICMP", "ICMP"),
                            ("ANY", "Tümü"),
                        ],
                        max_length=10,
                        verbose_name="Protokol",
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(verbose_name="Kaynak IP")),
                (
                    "source_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak Port"
                    ),
                ),
                (
                    "destination_ip",
                    models.GenericIPAddressField(verbose_name="Hedef IP"),
                ),
                (
                    "destination_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hedef Port"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "En Düşük"),
                            (2, "Düşük"),
                            (3, "Normal"),
                            (4, "Yüksek"),
                            (5, "En Yüksek"),
                        ],
                        default=3,
                        verbose_name="Öncelik",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Etkin")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geçerlilik Başlangıcı"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geçerlilik Bitişi"
                    ),
                ),
                (
                    "hit_count",
                    models.IntegerField(default=0, verbose_name="Eşleşme Sayısı"),
                ),
                (
                    "last_hit",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Eşleşme"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Duvarı Kuralı",
                "verbose_name_plural": "Güvenlik Duvarı Kuralları",
                "ordering": ["-priority", "created_at"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="FirewallPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Politika Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("SECURITY", "Güvenlik"),
                            ("COMPLIANCE", "Uyumluluk"),
                            ("PERFORMANCE", "Performans"),
                            ("MONITORING", "İzleme"),
                        ],
                        max_length=20,
                        verbose_name="Politika Tipi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True,
                        to="firewall_management.firewallrule",
                        verbose_name="Kurallar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Duvarı Politikası",
                "verbose_name_plural": "Güvenlik Duvarı Politikaları",
                "ordering": ["-created_at"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="FirewallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Zaman Damgası"
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(verbose_name="Kaynak IP")),
                (
                    "source_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak Port"
                    ),
                ),
                (
                    "destination_ip",
                    models.GenericIPAddressField(verbose_name="Hedef IP"),
                ),
                (
                    "destination_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hedef Port"
                    ),
                ),
                ("protocol", models.CharField(max_length=10, verbose_name="Protokol")),
                (
                    "action",
                    models.CharField(max_length=20, verbose_name="Uygulanan Aksiyon"),
                ),
                (
                    "bytes_sent",
                    models.BigIntegerField(default=0, verbose_name="Gönderilen Byte"),
                ),
                (
                    "bytes_received",
                    models.BigIntegerField(default=0, verbose_name="Alınan Byte"),
                ),
                (
                    "packets_sent",
                    models.IntegerField(default=0, verbose_name="Gönderilen Paket"),
                ),
                (
                    "packets_received",
                    models.IntegerField(default=0, verbose_name="Alınan Paket"),
                ),
                (
                    "connection_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Bağlantı Süresi"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="firewall_management.firewallrule",
                        verbose_name="Eşleşen Kural",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Duvarı Logu",
                "verbose_name_plural": "Güvenlik Duvarı Logları",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["company", "timestamp"],
                        name="firewall_ma_company_ca2959_idx",
                    ),
                    models.Index(
                        fields=["source_ip", "destination_ip"],
                        name="firewall_ma_source__c1fc44_idx",
                    ),
                    models.Index(
                        fields=["protocol", "action"],
                        name="firewall_ma_protoco_270773_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FirewallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("RULE_MATCH", "Kural Eşleşmesi"),
                            ("RULE_VIOLATION", "Kural İhlali"),
                            ("ATTACK_DETECTED", "Saldırı Tespit Edildi"),
                            ("TRAFFIC_ANOMALY", "Trafik Anomalisi"),
                            ("POLICY_UPDATE", "Politika Güncellendi"),
                            ("SYSTEM_ALERT", "Sistem Uyarısı"),
                        ],
                        max_length=20,
                        verbose_name="Olay Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Düşük"),
                            ("MEDIUM", "Orta"),
                            ("HIGH", "Yüksek"),
                            ("CRITICAL", "Kritik"),
                        ],
                        max_length=10,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(verbose_name="Kaynak IP")),
                (
                    "destination_ip",
                    models.GenericIPAddressField(verbose_name="Hedef IP"),
                ),
                ("protocol", models.CharField(max_length=10, verbose_name="Protokol")),
                (
                    "port",
                    models.IntegerField(blank=True, null=True, verbose_name="Port"),
                ),
                ("message", models.TextField(verbose_name="Olay Mesajı")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaylar"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Olay Zamanı"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Çözüldü"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="firewall_management.firewallpolicy",
                        verbose_name="İlgili Politika",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="firewall_management.firewallrule",
                        verbose_name="İlgili Kural",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik Duvarı Olayı",
                "verbose_name_plural": "Güvenlik Duvarı Olayları",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["company", "timestamp"],
                        name="firewall_ma_company_f3d60d_idx",
                    ),
                    models.Index(
                        fields=["event_type", "severity"],
                        name="firewall_ma_event_t_01b967_idx",
                    ),
                    models.Index(
                        fields=["source_ip", "destination_ip"],
                        name="firewall_ma_source__968db2_idx",
                    ),
                ],
            },
        ),
    ]
