# Generated by Django 4.2.7 on 2025-09-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firewall_management", "0002_alter_firewallrule_destination_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewalllog",
            name="destination_location",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Hedef Lokasyon"
            ),
        ),
        migrations.AddField(
            model_name="firewalllog",
            name="device_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Cihaz Adı"
            ),
        ),
        migrations.AddField(
            model_name="firewalllog",
            name="nat_destination_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="NAT Hedef IP"
            ),
        ),
        migrations.AddField(
            model_name="firewalllog",
            name="nat_destination_port",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="NAT Hedef Port"
            ),
        ),
        migrations.AddField(
            model_name="firewalllog",
            name="nat_source_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="NAT Kaynak IP"
            ),
        ),
        migrations.AddField(
            model_name="firewalllog",
            name="nat_source_port",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="NAT Kaynak Port"
            ),
        ),
        migrations.AddField(
            model_name="firewalllog",
            name="source_location",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Kaynak Lokasyon"
            ),
        ),
    ]
