# Generated by Django 4.2.7 on 2025-09-03 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0010_auto_20250621_0217"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Model Adı")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("traffic_prediction", "Trafik Tahmini"),
                            ("threat_prediction", "Tehdit Tahmini"),
                            ("performance_prediction", "Performans Tahmini"),
                            ("user_behavior_prediction", "Kullanıcı Davranış Tahmini"),
                        ],
                        max_length=50,
                        verbose_name="Model Tipi",
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Versiyon")),
                (
                    "accuracy",
                    models.FloatField(default=0.0, verbose_name="Doğruluk Oranı"),
                ),
                (
                    "last_trained",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Son Eğitim"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "model_config",
                    models.JSONField(default=dict, verbose_name="Model Konfigürasyonu"),
                ),
            ],
            options={
                "verbose_name": "Tahmin Modeli",
                "verbose_name_plural": "Tahmin Modelleri",
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Rapor Başlığı"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                            ("custom", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Rapor Tipi",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                (
                    "data_period_start",
                    models.DateTimeField(verbose_name="Veri Başlangıç"),
                ),
                ("data_period_end", models.DateTimeField(verbose_name="Veri Bitiş")),
                ("report_data", models.JSONField(verbose_name="Rapor Verisi")),
                (
                    "insights_count",
                    models.IntegerField(default=0, verbose_name="İçgörü Sayısı"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analiz Raporu",
                "verbose_name_plural": "Analiz Raporları",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Metrik Adı")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("network_traffic", "Network Trafik"),
                            ("user_behavior", "Kullanıcı Davranışı"),
                            ("security_threats", "Güvenlik Tehditleri"),
                            ("device_performance", "Cihaz Performansı"),
                            ("vpn_usage", "VPN Kullanımı"),
                            ("hotspot_activity", "Hotspot Aktivitesi"),
                            ("firewall_events", "Firewall Olayları"),
                        ],
                        max_length=50,
                        verbose_name="Metrik Tipi",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Değer")),
                ("unit", models.CharField(max_length=20, verbose_name="Birim")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Zaman"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analiz Metriği",
                "verbose_name_plural": "Analiz Metrikleri",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("anomaly", "Anomali Tespiti"),
                            ("trend", "Trend Analizi"),
                            ("prediction", "Tahmin"),
                            ("recommendation", "Öneri"),
                            ("risk_assessment", "Risk Değerlendirmesi"),
                        ],
                        max_length=50,
                        verbose_name="İçgörü Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("critical", "Kritik"),
                        ],
                        max_length=20,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="Güven Skoru"),
                ),
                (
                    "data_source",
                    models.CharField(max_length=100, verbose_name="Veri Kaynağı"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI İçgörüsü",
                "verbose_name_plural": "AI İçgörüleri",
                "ordering": ["-timestamp", "-severity"],
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(max_length=50, verbose_name="Kalıp Tipi"),
                ),
                ("pattern_data", models.JSONField(verbose_name="Kalıp Verisi")),
                (
                    "confidence",
                    models.FloatField(default=0.0, verbose_name="Güven Oranı"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="İlk Görülme"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Son Görülme"
                    ),
                ),
                ("frequency", models.IntegerField(default=1, verbose_name="Frekans")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Davranış Kalıbı",
                "verbose_name_plural": "Kullanıcı Davranış Kalıpları",
                "unique_together": {("user", "company", "pattern_type")},
            },
        ),
    ]
