# Generated by Django 4.2.7 on 2025-09-03 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yeni"),
                            ("acknowledged", "Kabul Edildi"),
                            ("in_progress", "İşlemde"),
                            ("resolved", "Çözüldü"),
                            ("closed", "Kapatıldı"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Bilgi"),
                            ("warning", "Uyarı"),
                            ("error", "Hata"),
                            ("critical", "Kritik"),
                        ],
                        max_length=20,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Tetiklenme Zamanı",
                    ),
                ),
                ("trigger_data", models.JSONField(verbose_name="Tetikleyici Verisi")),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kabul Edilme Zamanı"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Çözüm Notları"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Zamanı"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_system_acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kabul Eden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uyarı",
                "verbose_name_plural": "Uyarılar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şablon Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("security", "Güvenlik"),
                            ("performance", "Performans"),
                            ("network", "Network"),
                            ("device", "Cihaz"),
                            ("user", "Kullanıcı"),
                            ("system", "Sistem"),
                        ],
                        max_length=20,
                        verbose_name="Uyarı Tipi",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(max_length=200, verbose_name="Konu Şablonu"),
                ),
                ("message_template", models.TextField(verbose_name="Mesaj Şablonu")),
                (
                    "html_template",
                    models.TextField(blank=True, verbose_name="HTML Şablonu"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uyarı Şablonu",
                "verbose_name_plural": "Uyarı Şablonları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Kural Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("security", "Güvenlik"),
                            ("performance", "Performans"),
                            ("network", "Network"),
                            ("device", "Cihaz"),
                            ("user", "Kullanıcı"),
                            ("system", "Sistem"),
                        ],
                        max_length=20,
                        verbose_name="Uyarı Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Bilgi"),
                            ("warning", "Uyarı"),
                            ("error", "Hata"),
                            ("critical", "Kritik"),
                        ],
                        max_length=20,
                        verbose_name="Önem Seviyesi",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Eşik Değeri"),
                            ("anomaly", "Anomali"),
                            ("pattern", "Kalıp"),
                            ("schedule", "Zamanlanmış"),
                            ("manual", "Manuel"),
                        ],
                        max_length=20,
                        verbose_name="Tetikleyici Tipi",
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(verbose_name="Tetikleyici Koşulları"),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Eşik Değeri"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "auto_resolve",
                    models.BooleanField(default=False, verbose_name="Otomatik Çözüm"),
                ),
                (
                    "escalation_enabled",
                    models.BooleanField(default=False, verbose_name="Yükseltme Aktif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uyarı Kuralı",
                "verbose_name_plural": "Uyarı Kuralları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("sms", "SMS"),
                            ("push", "Push Bildirim"),
                            ("webhook", "Webhook"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                        ],
                        max_length=20,
                        verbose_name="Bildirim Tipi",
                    ),
                ),
                ("recipient", models.CharField(max_length=200, verbose_name="Alıcı")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderilme Zamanı"
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="Teslim Durumu"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alert_system.alert",
                        verbose_name="Uyarı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uyarı Bildirimi",
                "verbose_name_plural": "Uyarı Bildirimleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="alert_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alert_system.alertrule",
                verbose_name="Uyarı Kuralı",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="log_kayit.company",
                verbose_name="Şirket",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_system_resolved_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Çözen",
            ),
        ),
        migrations.CreateModel(
            name="AlertEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escalation_level",
                    models.IntegerField(verbose_name="Yükseltme Seviyesi"),
                ),
                ("delay_minutes", models.IntegerField(verbose_name="Gecikme (Dakika)")),
                ("notify_roles", models.JSONField(verbose_name="Bildirilecek Roller")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Zamanı",
                    ),
                ),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alert_system.alertrule",
                        verbose_name="Uyarı Kuralı",
                    ),
                ),
                (
                    "notify_users",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bildirilecek Kullanıcılar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uyarı Yükseltmesi",
                "verbose_name_plural": "Uyarı Yükseltmeleri",
                "ordering": ["escalation_level"],
                "unique_together": {("alert_rule", "escalation_level")},
            },
        ),
    ]
