# Generated by Django 4.2.7 on 2025-09-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Cihaz Adı")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ROUTER", "Router"),
                            ("SWITCH", "Switch"),
                            ("FIREWALL", "Firewall"),
                            ("ACCESS_POINT", "Access Point"),
                            ("SERVER", "Server"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=50,
                        verbose_name="Cihaz Türü",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "mac_address",
                    models.CharField(max_length=17, verbose_name="MAC Adresi"),
                ),
                (
                    "subnet_mask",
                    models.GenericIPAddressField(
                        default="255.255.255.0", verbose_name="Subnet Mask"
                    ),
                ),
                (
                    "gateway",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Gateway"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Model"),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Üretici"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Firmware Versiyonu"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Seri No"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Çevrimiçi"),
                            ("OFFLINE", "Çevrimdışı"),
                            ("WARNING", "Uyarı"),
                            ("CRITICAL", "Kritik"),
                            ("MAINTENANCE", "Bakımda"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(default=0, verbose_name="CPU Kullanımı (%)"),
                ),
                (
                    "memory_usage",
                    models.FloatField(default=0, verbose_name="RAM Kullanımı (%)"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Sıcaklık (°C)"
                    ),
                ),
                (
                    "uptime",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Çalışma Süresi"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Son Görülme"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_devices",
                        to="log_kayit.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Cihazı",
                "verbose_name_plural": "Network Cihazları",
                "ordering": ["-last_seen"],
                "unique_together": {("company", "ip_address")},
            },
        ),
        migrations.CreateModel(
            name="NetworkTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(verbose_name="Kaynak IP")),
                (
                    "destination_ip",
                    models.GenericIPAddressField(verbose_name="Hedef IP"),
                ),
                ("source_port", models.IntegerField(verbose_name="Kaynak Port")),
                ("destination_port", models.IntegerField(verbose_name="Hedef Port")),
                ("protocol", models.CharField(max_length=10, verbose_name="Protokol")),
                (
                    "bytes_sent",
                    models.BigIntegerField(
                        default=0, verbose_name="Gönderilen Veri (byte)"
                    ),
                ),
                (
                    "bytes_received",
                    models.BigIntegerField(
                        default=0, verbose_name="Alınan Veri (byte)"
                    ),
                ),
                (
                    "packets_sent",
                    models.BigIntegerField(default=0, verbose_name="Gönderilen Paket"),
                ),
                (
                    "packets_received",
                    models.BigIntegerField(default=0, verbose_name="Alınan Paket"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Başlangıç Zamanı")),
                ("end_time", models.DateTimeField(verbose_name="Bitiş Zamanı")),
                ("duration", models.FloatField(verbose_name="Süre (saniye)")),
                (
                    "application",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Uygulama"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_traffic",
                        to="log_kayit.company",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_logs",
                        to="network_monitoring.networkdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Trafik",
                "verbose_name_plural": "Network Trafik",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["company", "start_time"],
                        name="network_mon_company_523aaa_idx",
                    ),
                    models.Index(
                        fields=["device", "start_time"],
                        name="network_mon_device__223026_idx",
                    ),
                    models.Index(
                        fields=["source_ip", "start_time"],
                        name="network_mon_source__ab9d12_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NetworkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("CONNECTION", "Bağlantı"),
                            ("TRAFFIC", "Trafik"),
                            ("ERROR", "Hata"),
                            ("SECURITY", "Güvenlik"),
                            ("SYSTEM", "Sistem"),
                            ("USER_ACTIVITY", "Kullanıcı Aktivitesi"),
                        ],
                        max_length=50,
                        verbose_name="Log Türü",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Bilgi"),
                            ("WARNING", "Uyarı"),
                            ("ERROR", "Hata"),
                            ("CRITICAL", "Kritik"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="Seviye",
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Kaynak IP"
                    ),
                ),
                (
                    "destination_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Hedef IP"
                    ),
                ),
                (
                    "source_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak Port"
                    ),
                ),
                (
                    "destination_port",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hedef Port"
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Protokol"
                    ),
                ),
                (
                    "bytes_transferred",
                    models.BigIntegerField(
                        default=0, verbose_name="Transfer Edilen Veri (byte)"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Süre (saniye)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_logs",
                        to="log_kayit.company",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="network_monitoring.networkdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Log",
                "verbose_name_plural": "Network Logları",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["company", "timestamp"],
                        name="network_mon_company_f89dc5_idx",
                    ),
                    models.Index(
                        fields=["device", "timestamp"],
                        name="network_mon_device__e40354_idx",
                    ),
                    models.Index(
                        fields=["log_type", "timestamp"],
                        name="network_mon_log_typ_7b2b92_idx",
                    ),
                ],
            },
        ),
    ]
