# Generated by Django 4.2.7 on 2025-09-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_kayit", "0010_auto_20250621_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="BandwidthPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Politika Adı")),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("FREE", "Ücretsiz"),
                            ("PREMIUM", "Premium"),
                            ("BUSINESS", "İş"),
                            ("GUEST", "Misafir"),
                            ("STAFF", "Personel"),
                        ],
                        max_length=20,
                        verbose_name="Politika Tipi",
                    ),
                ),
                (
                    "download_limit_mbps",
                    models.IntegerField(verbose_name="Download Limiti (Mbps)"),
                ),
                (
                    "upload_limit_mbps",
                    models.IntegerField(verbose_name="Upload Limiti (Mbps)"),
                ),
                (
                    "daily_limit_gb",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Günlük Limit (GB)",
                    ),
                ),
                ("priority", models.IntegerField(default=1, verbose_name="Öncelik")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bant Genişliği Politikası",
                "verbose_name_plural": "Bant Genişliği Politikaları",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="HotspotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Hotspot Adı")),
                ("ssid", models.CharField(max_length=32, verbose_name="SSID")),
                (
                    "password",
                    models.CharField(blank=True, max_length=64, verbose_name="Şifre"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Herkese Açık"),
                ),
                (
                    "max_bandwidth_mbps",
                    models.IntegerField(
                        default=10, verbose_name="Maksimum Bant Genişliği (Mbps)"
                    ),
                ),
                (
                    "max_upload_mbps",
                    models.IntegerField(
                        default=5, verbose_name="Maksimum Upload (Mbps)"
                    ),
                ),
                (
                    "max_download_mbps",
                    models.IntegerField(
                        default=10, verbose_name="Maksimum Download (Mbps)"
                    ),
                ),
                (
                    "session_timeout_hours",
                    models.IntegerField(
                        default=24, verbose_name="Oturum Zaman Aşımı (Saat)"
                    ),
                ),
                (
                    "max_concurrent_users",
                    models.IntegerField(
                        default=100, verbose_name="Maksimum Eş Zamanlı Kullanıcı"
                    ),
                ),
                (
                    "enable_content_filtering",
                    models.BooleanField(
                        default=True, verbose_name="İçerik Filtreleme Aktif"
                    ),
                ),
                (
                    "block_adult_content",
                    models.BooleanField(
                        default=True, verbose_name="Yetişkin İçeriği Engelle"
                    ),
                ),
                (
                    "block_gambling",
                    models.BooleanField(
                        default=True, verbose_name="Kumar Sitelerini Engelle"
                    ),
                ),
                (
                    "block_social_media",
                    models.BooleanField(
                        default=False, verbose_name="Sosyal Medyayı Engelle"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(default="00:00", verbose_name="Başlangıç Saati"),
                ),
                (
                    "end_time",
                    models.TimeField(default="23:59", verbose_name="Bitiş Saati"),
                ),
                (
                    "is_24_7",
                    models.BooleanField(default=True, verbose_name="7/24 Aktif"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotspot Konfigürasyonu",
                "verbose_name_plural": "Hotspot Konfigürasyonları",
                "unique_together": {("company", "ssid")},
            },
        ),
        migrations.CreateModel(
            name="HotspotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Kullanıcı Adı"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("GUEST", "Misafir"),
                            ("REGISTERED", "Kayıtlı"),
                            ("STAFF", "Personel"),
                            ("VIP", "VIP"),
                        ],
                        default="GUEST",
                        max_length=20,
                        verbose_name="Kullanıcı Tipi",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(max_length=17, verbose_name="MAC Adresi"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "device_info",
                    models.TextField(blank=True, verbose_name="Cihaz Bilgisi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Engellenmiş"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Giriş"
                    ),
                ),
                (
                    "bandwidth_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotspot_management.bandwidthpolicy",
                        verbose_name="Bant Genişliği Politikası",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "hotspot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotspot_management.hotspotconfiguration",
                        verbose_name="Hotspot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotspot Kullanıcısı",
                "verbose_name_plural": "Hotspot Kullanıcıları",
                "unique_together": {("company", "mac_address")},
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Oturum ID"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Başlangıç Zamanı"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Zamanı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("EXPIRED", "Süresi Dolmuş"),
                            ("TERMINATED", "Sonlandırıldı"),
                            ("BLOCKED", "Engellenmiş"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "bytes_uploaded",
                    models.BigIntegerField(default=0, verbose_name="Upload (Byte)"),
                ),
                (
                    "bytes_downloaded",
                    models.BigIntegerField(default=0, verbose_name="Download (Byte)"),
                ),
                (
                    "total_bytes",
                    models.BigIntegerField(default=0, verbose_name="Toplam (Byte)"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, verbose_name="Süre (Dakika)"),
                ),
                (
                    "hotspot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotspot_management.hotspotconfiguration",
                        verbose_name="Hotspot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotspot_management.hotspotuser",
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Oturumu",
                "verbose_name_plural": "Kullanıcı Oturumları",
            },
        ),
        migrations.CreateModel(
            name="ContentFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kural Adı")),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("URL", "URL"),
                            ("DOMAIN", "Domain"),
                            ("IP", "IP Adresi"),
                            ("KEYWORD", "Anahtar Kelime"),
                            ("CATEGORY", "Kategori"),
                        ],
                        max_length=20,
                        verbose_name="Filtre Tipi",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("BLOCK", "Engelle"),
                            ("ALLOW", "İzin Ver"),
                            ("WARN", "Uyarı Ver"),
                            ("LOG", "Sadece Logla"),
                        ],
                        max_length=20,
                        verbose_name="Aksiyon",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=500, verbose_name="Filtre Değeri"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("priority", models.IntegerField(default=1, verbose_name="Öncelik")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "İçerik Filtresi",
                "verbose_name_plural": "İçerik Filtreleri",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="HotspotMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("hour", models.IntegerField(verbose_name="Saat")),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="Aktif Kullanıcı"),
                ),
                (
                    "total_sessions",
                    models.IntegerField(default=0, verbose_name="Toplam Oturum"),
                ),
                (
                    "new_users",
                    models.IntegerField(default=0, verbose_name="Yeni Kullanıcı"),
                ),
                (
                    "bandwidth_used_mbps",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kullanılan Bant Genişliği (Mbps)",
                    ),
                ),
                (
                    "peak_bandwidth_mbps",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Pik Bant Genişliği (Mbps)",
                    ),
                ),
                (
                    "blocked_requests",
                    models.IntegerField(default=0, verbose_name="Engellenen İstek"),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="Toplam İstek"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_kayit.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "hotspot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotspot_management.hotspotconfiguration",
                        verbose_name="Hotspot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotspot Metriği",
                "verbose_name_plural": "Hotspot Metrikleri",
                "indexes": [
                    models.Index(
                        fields=["date", "hour"], name="hotspot_man_date_638e9e_idx"
                    ),
                    models.Index(
                        fields=["company", "date"],
                        name="hotspot_man_company_e7a3bf_idx",
                    ),
                ],
                "unique_together": {("company", "hotspot", "date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                ("domain", models.CharField(max_length=255, verbose_name="Domain")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "was_blocked",
                    models.BooleanField(default=False, verbose_name="Engellendi mi?"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "content_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotspot_management.contentfilter",
                        verbose_name="İçerik Filtresi",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotspot_management.usersession",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotspot_management.hotspotuser",
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erişim Logu",
                "verbose_name_plural": "Erişim Logları",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="hotspot_man_timesta_632d50_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="hotspot_man_user_id_60ea20_idx",
                    ),
                    models.Index(
                        fields=["domain"], name="hotspot_man_domain_0babd1_idx"
                    ),
                ],
            },
        ),
    ]
