# Generated by Django 4.2.7 on 2025-09-03 19:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VPNProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Proje Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "vpn_server_ip",
                    models.GenericIPAddressField(verbose_name="VPN Sunucu IP"),
                ),
                (
                    "vpn_server_port",
                    models.IntegerField(default=1194, verbose_name="VPN Port"),
                ),
                (
                    "vpn_protocol",
                    models.CharField(
                        choices=[
                            ("openvpn", "OpenVPN"),
                            ("wireguard", "WireGuard"),
                            ("ipsec", "IPSec"),
                            ("l2tp", "L2TP"),
                            ("pptp", "PPTP"),
                        ],
                        default="openvpn",
                        max_length=20,
                        verbose_name="VPN Protokolü",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Projesi",
                "verbose_name_plural": "VPN Projeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Bağlantı ID"
                    ),
                ),
                ("vpn_ip", models.GenericIPAddressField(verbose_name="VPN IP Adresi")),
                (
                    "real_ip",
                    models.GenericIPAddressField(verbose_name="Gerçek IP Adresi"),
                ),
                (
                    "local_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Yerel IP"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connecting", "Bağlanıyor"),
                            ("connected", "Bağlı"),
                            ("disconnected", "Bağlantı Kesildi"),
                            ("error", "Hata"),
                        ],
                        default="connecting",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("connected_at", models.DateTimeField(verbose_name="Bağlanma Zamanı")),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çıkış Zamanı"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Bağlantı Süresi"
                    ),
                ),
                (
                    "bandwidth_in",
                    models.BigIntegerField(
                        default=0, verbose_name="Gelen Trafik (bytes)"
                    ),
                ),
                (
                    "bandwidth_out",
                    models.BigIntegerField(
                        default=0, verbose_name="Giden Trafik (bytes)"
                    ),
                ),
                (
                    "packets_in",
                    models.BigIntegerField(default=0, verbose_name="Gelen Paket"),
                ),
                (
                    "packets_out",
                    models.BigIntegerField(default=0, verbose_name="Giden Paket"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "disconnect_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user_disconnect", "Kullanıcı Çıkış"),
                            ("timeout", "Zaman Aşımı"),
                            ("server_error", "Sunucu Hatası"),
                            ("network_error", "Ağ Hatası"),
                            ("system_crash", "Sistem Çökmesi"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Çıkış Nedeni",
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="Cihaz Bilgileri"),
                ),
                (
                    "location_info",
                    models.JSONField(default=dict, verbose_name="Konum Bilgileri"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vpn_monitoring.vpnproject",
                        verbose_name="Proje",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Bağlantısı",
                "verbose_name_plural": "VPN Bağlantıları",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNUserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Giriş"),
                            ("logout", "Çıkış"),
                            ("reconnect", "Yeniden Bağlanma"),
                            ("timeout", "Zaman Aşımı"),
                            ("error", "Hata"),
                            ("bandwidth_update", "Trafik Güncelleme"),
                            ("ip_change", "IP Değişikliği"),
                        ],
                        max_length=50,
                        verbose_name="Aktivite Tipi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="Ek Bilgiler"),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vpn_monitoring.vpnconnection",
                        verbose_name="Bağlantı",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vpn_monitoring.vpnproject",
                        verbose_name="Proje",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Kullanıcı Aktivitesi",
                "verbose_name_plural": "VPN Kullanıcı Aktiviteleri",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "project", "timestamp"],
                        name="vpn_monitor_user_id_d06329_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "timestamp"],
                        name="vpn_monitor_activit_ad2b59_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VPNServerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Çevrimiçi"),
                            ("offline", "Çevrimdışı"),
                            ("maintenance", "Bakım"),
                            ("error", "Hata"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="CPU Kullanımı (%)",
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="RAM Kullanımı (%)",
                    ),
                ),
                (
                    "disk_usage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Disk Kullanımı (%)",
                    ),
                ),
                (
                    "active_connections",
                    models.IntegerField(default=0, verbose_name="Aktif Bağlantı"),
                ),
                (
                    "total_bandwidth_in",
                    models.BigIntegerField(
                        default=0, verbose_name="Toplam Gelen Trafik"
                    ),
                ),
                (
                    "total_bandwidth_out",
                    models.BigIntegerField(
                        default=0, verbose_name="Toplam Giden Trafik"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "last_check",
                    models.DateTimeField(auto_now=True, verbose_name="Son Kontrol"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vpn_monitoring.vpnproject",
                        verbose_name="Proje",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Sunucu Durumu",
                "verbose_name_plural": "VPN Sunucu Durumları",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["project", "timestamp"],
                        name="vpn_monitor_project_243ebe_idx",
                    ),
                    models.Index(
                        fields=["status", "timestamp"],
                        name="vpn_monitor_status_185806_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vpnconnection",
            index=models.Index(
                fields=["user", "project"], name="vpn_monitor_user_id_680bf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnconnection",
            index=models.Index(
                fields=["status", "connected_at"], name="vpn_monitor_status_11615d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnconnection",
            index=models.Index(
                fields=["vpn_ip", "real_ip"], name="vpn_monitor_vpn_ip_ab3fd5_idx"
            ),
        ),
    ]
